// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room/room_types.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_room_2froom_5ftypes_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_room_2froom_5ftypes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common/common_types.pb.h"
#include "common/common_enums.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_room_2froom_5ftypes_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_room_2froom_5ftypes_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_room_2froom_5ftypes_2eproto;
namespace se {
namespace room {
class ItemSpawnInfo;
struct ItemSpawnInfoDefaultTypeInternal;
extern ItemSpawnInfoDefaultTypeInternal _ItemSpawnInfo_default_instance_;
class MonsterSpawnInfo;
struct MonsterSpawnInfoDefaultTypeInternal;
extern MonsterSpawnInfoDefaultTypeInternal _MonsterSpawnInfo_default_instance_;
class PlayerSpawnInfo;
struct PlayerSpawnInfoDefaultTypeInternal;
extern PlayerSpawnInfoDefaultTypeInternal _PlayerSpawnInfo_default_instance_;
class ProjectileSpawnInfo;
struct ProjectileSpawnInfoDefaultTypeInternal;
extern ProjectileSpawnInfoDefaultTypeInternal _ProjectileSpawnInfo_default_instance_;
class RoomPlayer;
struct RoomPlayerDefaultTypeInternal;
extern RoomPlayerDefaultTypeInternal _RoomPlayer_default_instance_;
class RoomSnapshot;
struct RoomSnapshotDefaultTypeInternal;
extern RoomSnapshotDefaultTypeInternal _RoomSnapshot_default_instance_;
class SpawnInfo;
struct SpawnInfoDefaultTypeInternal;
extern SpawnInfoDefaultTypeInternal _SpawnInfo_default_instance_;
}  // namespace room
}  // namespace se
PROTOBUF_NAMESPACE_OPEN
template<> ::se::room::ItemSpawnInfo* Arena::CreateMaybeMessage<::se::room::ItemSpawnInfo>(Arena*);
template<> ::se::room::MonsterSpawnInfo* Arena::CreateMaybeMessage<::se::room::MonsterSpawnInfo>(Arena*);
template<> ::se::room::PlayerSpawnInfo* Arena::CreateMaybeMessage<::se::room::PlayerSpawnInfo>(Arena*);
template<> ::se::room::ProjectileSpawnInfo* Arena::CreateMaybeMessage<::se::room::ProjectileSpawnInfo>(Arena*);
template<> ::se::room::RoomPlayer* Arena::CreateMaybeMessage<::se::room::RoomPlayer>(Arena*);
template<> ::se::room::RoomSnapshot* Arena::CreateMaybeMessage<::se::room::RoomSnapshot>(Arena*);
template<> ::se::room::SpawnInfo* Arena::CreateMaybeMessage<::se::room::SpawnInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace se {
namespace room {

// ===================================================================

class RoomPlayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.RoomPlayer) */ {
 public:
  inline RoomPlayer() : RoomPlayer(nullptr) {}
  ~RoomPlayer() override;
  explicit PROTOBUF_CONSTEXPR RoomPlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoomPlayer(const RoomPlayer& from);
  RoomPlayer(RoomPlayer&& from) noexcept
    : RoomPlayer() {
    *this = ::std::move(from);
  }

  inline RoomPlayer& operator=(const RoomPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomPlayer& operator=(RoomPlayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoomPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoomPlayer* internal_default_instance() {
    return reinterpret_cast<const RoomPlayer*>(
               &_RoomPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoomPlayer& a, RoomPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomPlayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoomPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoomPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoomPlayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoomPlayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoomPlayer& from) {
    RoomPlayer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomPlayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.RoomPlayer";
  }
  protected:
  explicit RoomPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 3,
    kPlayerIdFieldNumber = 1,
    kEntityIdFieldNumber = 2,
  };
  // string nickname = 3;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // .se.common.PlayerId player_id = 1;
  bool has_player_id() const;
  private:
  bool _internal_has_player_id() const;
  public:
  void clear_player_id();
  const ::se::common::PlayerId& player_id() const;
  PROTOBUF_NODISCARD ::se::common::PlayerId* release_player_id();
  ::se::common::PlayerId* mutable_player_id();
  void set_allocated_player_id(::se::common::PlayerId* player_id);
  private:
  const ::se::common::PlayerId& _internal_player_id() const;
  ::se::common::PlayerId* _internal_mutable_player_id();
  public:
  void unsafe_arena_set_allocated_player_id(
      ::se::common::PlayerId* player_id);
  ::se::common::PlayerId* unsafe_arena_release_player_id();

  // .se.common.ObjectId entity_id = 2;
  bool has_entity_id() const;
  private:
  bool _internal_has_entity_id() const;
  public:
  void clear_entity_id();
  const ::se::common::ObjectId& entity_id() const;
  PROTOBUF_NODISCARD ::se::common::ObjectId* release_entity_id();
  ::se::common::ObjectId* mutable_entity_id();
  void set_allocated_entity_id(::se::common::ObjectId* entity_id);
  private:
  const ::se::common::ObjectId& _internal_entity_id() const;
  ::se::common::ObjectId* _internal_mutable_entity_id();
  public:
  void unsafe_arena_set_allocated_entity_id(
      ::se::common::ObjectId* entity_id);
  ::se::common::ObjectId* unsafe_arena_release_entity_id();

  // @@protoc_insertion_point(class_scope:se.room.RoomPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    ::se::common::PlayerId* player_id_;
    ::se::common::ObjectId* entity_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class RoomSnapshot final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.RoomSnapshot) */ {
 public:
  inline RoomSnapshot() : RoomSnapshot(nullptr) {}
  ~RoomSnapshot() override;
  explicit PROTOBUF_CONSTEXPR RoomSnapshot(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoomSnapshot(const RoomSnapshot& from);
  RoomSnapshot(RoomSnapshot&& from) noexcept
    : RoomSnapshot() {
    *this = ::std::move(from);
  }

  inline RoomSnapshot& operator=(const RoomSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomSnapshot& operator=(RoomSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoomSnapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoomSnapshot* internal_default_instance() {
    return reinterpret_cast<const RoomSnapshot*>(
               &_RoomSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RoomSnapshot& a, RoomSnapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomSnapshot* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoomSnapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoomSnapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoomSnapshot>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoomSnapshot& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoomSnapshot& from) {
    RoomSnapshot::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomSnapshot* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.RoomSnapshot";
  }
  protected:
  explicit RoomSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 2,
    kRoomIdFieldNumber = 1,
  };
  // repeated .se.room.RoomPlayer players = 2;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::se::room::RoomPlayer* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::se::room::RoomPlayer >*
      mutable_players();
  private:
  const ::se::room::RoomPlayer& _internal_players(int index) const;
  ::se::room::RoomPlayer* _internal_add_players();
  public:
  const ::se::room::RoomPlayer& players(int index) const;
  ::se::room::RoomPlayer* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::se::room::RoomPlayer >&
      players() const;

  // uint32 room_id = 1;
  void clear_room_id();
  uint32_t room_id() const;
  void set_room_id(uint32_t value);
  private:
  uint32_t _internal_room_id() const;
  void _internal_set_room_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.room.RoomSnapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::se::room::RoomPlayer > players_;
    uint32_t room_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class PlayerSpawnInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.PlayerSpawnInfo) */ {
 public:
  inline PlayerSpawnInfo() : PlayerSpawnInfo(nullptr) {}
  ~PlayerSpawnInfo() override;
  explicit PROTOBUF_CONSTEXPR PlayerSpawnInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerSpawnInfo(const PlayerSpawnInfo& from);
  PlayerSpawnInfo(PlayerSpawnInfo&& from) noexcept
    : PlayerSpawnInfo() {
    *this = ::std::move(from);
  }

  inline PlayerSpawnInfo& operator=(const PlayerSpawnInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerSpawnInfo& operator=(PlayerSpawnInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerSpawnInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerSpawnInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerSpawnInfo*>(
               &_PlayerSpawnInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlayerSpawnInfo& a, PlayerSpawnInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerSpawnInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerSpawnInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerSpawnInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerSpawnInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerSpawnInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerSpawnInfo& from) {
    PlayerSpawnInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerSpawnInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.PlayerSpawnInfo";
  }
  protected:
  explicit PlayerSpawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMovementFieldNumber = 1,
  };
  // .se.common.MovementState movement = 1;
  bool has_movement() const;
  private:
  bool _internal_has_movement() const;
  public:
  void clear_movement();
  const ::se::common::MovementState& movement() const;
  PROTOBUF_NODISCARD ::se::common::MovementState* release_movement();
  ::se::common::MovementState* mutable_movement();
  void set_allocated_movement(::se::common::MovementState* movement);
  private:
  const ::se::common::MovementState& _internal_movement() const;
  ::se::common::MovementState* _internal_mutable_movement();
  public:
  void unsafe_arena_set_allocated_movement(
      ::se::common::MovementState* movement);
  ::se::common::MovementState* unsafe_arena_release_movement();

  // @@protoc_insertion_point(class_scope:se.room.PlayerSpawnInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::MovementState* movement_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class MonsterSpawnInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.MonsterSpawnInfo) */ {
 public:
  inline MonsterSpawnInfo() : MonsterSpawnInfo(nullptr) {}
  ~MonsterSpawnInfo() override;
  explicit PROTOBUF_CONSTEXPR MonsterSpawnInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MonsterSpawnInfo(const MonsterSpawnInfo& from);
  MonsterSpawnInfo(MonsterSpawnInfo&& from) noexcept
    : MonsterSpawnInfo() {
    *this = ::std::move(from);
  }

  inline MonsterSpawnInfo& operator=(const MonsterSpawnInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline MonsterSpawnInfo& operator=(MonsterSpawnInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MonsterSpawnInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const MonsterSpawnInfo* internal_default_instance() {
    return reinterpret_cast<const MonsterSpawnInfo*>(
               &_MonsterSpawnInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MonsterSpawnInfo& a, MonsterSpawnInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(MonsterSpawnInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MonsterSpawnInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MonsterSpawnInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MonsterSpawnInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MonsterSpawnInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MonsterSpawnInfo& from) {
    MonsterSpawnInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MonsterSpawnInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.MonsterSpawnInfo";
  }
  protected:
  explicit MonsterSpawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMovementFieldNumber = 1,
  };
  // .se.common.MovementState movement = 1;
  bool has_movement() const;
  private:
  bool _internal_has_movement() const;
  public:
  void clear_movement();
  const ::se::common::MovementState& movement() const;
  PROTOBUF_NODISCARD ::se::common::MovementState* release_movement();
  ::se::common::MovementState* mutable_movement();
  void set_allocated_movement(::se::common::MovementState* movement);
  private:
  const ::se::common::MovementState& _internal_movement() const;
  ::se::common::MovementState* _internal_mutable_movement();
  public:
  void unsafe_arena_set_allocated_movement(
      ::se::common::MovementState* movement);
  ::se::common::MovementState* unsafe_arena_release_movement();

  // @@protoc_insertion_point(class_scope:se.room.MonsterSpawnInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::MovementState* movement_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class ItemSpawnInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.ItemSpawnInfo) */ {
 public:
  inline ItemSpawnInfo() : ItemSpawnInfo(nullptr) {}
  ~ItemSpawnInfo() override;
  explicit PROTOBUF_CONSTEXPR ItemSpawnInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ItemSpawnInfo(const ItemSpawnInfo& from);
  ItemSpawnInfo(ItemSpawnInfo&& from) noexcept
    : ItemSpawnInfo() {
    *this = ::std::move(from);
  }

  inline ItemSpawnInfo& operator=(const ItemSpawnInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemSpawnInfo& operator=(ItemSpawnInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ItemSpawnInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ItemSpawnInfo* internal_default_instance() {
    return reinterpret_cast<const ItemSpawnInfo*>(
               &_ItemSpawnInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ItemSpawnInfo& a, ItemSpawnInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemSpawnInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemSpawnInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ItemSpawnInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ItemSpawnInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ItemSpawnInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ItemSpawnInfo& from) {
    ItemSpawnInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemSpawnInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.ItemSpawnInfo";
  }
  protected:
  explicit ItemSpawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kVelocityFieldNumber = 2,
    kAmountFieldNumber = 3,
  };
  // .se.common.Vector3 position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::se::common::Vector3& position() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_position();
  ::se::common::Vector3* mutable_position();
  void set_allocated_position(::se::common::Vector3* position);
  private:
  const ::se::common::Vector3& _internal_position() const;
  ::se::common::Vector3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::se::common::Vector3* position);
  ::se::common::Vector3* unsafe_arena_release_position();

  // .se.common.Vector3 velocity = 2;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::se::common::Vector3& velocity() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_velocity();
  ::se::common::Vector3* mutable_velocity();
  void set_allocated_velocity(::se::common::Vector3* velocity);
  private:
  const ::se::common::Vector3& _internal_velocity() const;
  ::se::common::Vector3* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::se::common::Vector3* velocity);
  ::se::common::Vector3* unsafe_arena_release_velocity();

  // uint32 amount = 3;
  void clear_amount();
  uint32_t amount() const;
  void set_amount(uint32_t value);
  private:
  uint32_t _internal_amount() const;
  void _internal_set_amount(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.room.ItemSpawnInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::Vector3* position_;
    ::se::common::Vector3* velocity_;
    uint32_t amount_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class ProjectileSpawnInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.ProjectileSpawnInfo) */ {
 public:
  inline ProjectileSpawnInfo() : ProjectileSpawnInfo(nullptr) {}
  ~ProjectileSpawnInfo() override;
  explicit PROTOBUF_CONSTEXPR ProjectileSpawnInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProjectileSpawnInfo(const ProjectileSpawnInfo& from);
  ProjectileSpawnInfo(ProjectileSpawnInfo&& from) noexcept
    : ProjectileSpawnInfo() {
    *this = ::std::move(from);
  }

  inline ProjectileSpawnInfo& operator=(const ProjectileSpawnInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProjectileSpawnInfo& operator=(ProjectileSpawnInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProjectileSpawnInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProjectileSpawnInfo* internal_default_instance() {
    return reinterpret_cast<const ProjectileSpawnInfo*>(
               &_ProjectileSpawnInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ProjectileSpawnInfo& a, ProjectileSpawnInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ProjectileSpawnInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProjectileSpawnInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProjectileSpawnInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProjectileSpawnInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProjectileSpawnInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProjectileSpawnInfo& from) {
    ProjectileSpawnInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProjectileSpawnInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.ProjectileSpawnInfo";
  }
  protected:
  explicit ProjectileSpawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kVelocityFieldNumber = 2,
  };
  // .se.common.Vector3 position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::se::common::Vector3& position() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_position();
  ::se::common::Vector3* mutable_position();
  void set_allocated_position(::se::common::Vector3* position);
  private:
  const ::se::common::Vector3& _internal_position() const;
  ::se::common::Vector3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::se::common::Vector3* position);
  ::se::common::Vector3* unsafe_arena_release_position();

  // .se.common.Vector3 velocity = 2;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::se::common::Vector3& velocity() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_velocity();
  ::se::common::Vector3* mutable_velocity();
  void set_allocated_velocity(::se::common::Vector3* velocity);
  private:
  const ::se::common::Vector3& _internal_velocity() const;
  ::se::common::Vector3* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::se::common::Vector3* velocity);
  ::se::common::Vector3* unsafe_arena_release_velocity();

  // @@protoc_insertion_point(class_scope:se.room.ProjectileSpawnInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::Vector3* position_;
    ::se::common::Vector3* velocity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class SpawnInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.room.SpawnInfo) */ {
 public:
  inline SpawnInfo() : SpawnInfo(nullptr) {}
  ~SpawnInfo() override;
  explicit PROTOBUF_CONSTEXPR SpawnInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpawnInfo(const SpawnInfo& from);
  SpawnInfo(SpawnInfo&& from) noexcept
    : SpawnInfo() {
    *this = ::std::move(from);
  }

  inline SpawnInfo& operator=(const SpawnInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpawnInfo& operator=(SpawnInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpawnInfo& default_instance() {
    return *internal_default_instance();
  }
  enum DetailCase {
    kPlayerInfo = 10,
    kMonsterInfo = 11,
    kItemInfo = 12,
    kProjectileInfo = 13,
    DETAIL_NOT_SET = 0,
  };

  static inline const SpawnInfo* internal_default_instance() {
    return reinterpret_cast<const SpawnInfo*>(
               &_SpawnInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(SpawnInfo& a, SpawnInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(SpawnInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpawnInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpawnInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpawnInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpawnInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpawnInfo& from) {
    SpawnInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpawnInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.room.SpawnInfo";
  }
  protected:
  explicit SpawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityIdFieldNumber = 3,
    kTypeFieldNumber = 1,
    kTemplateIdFieldNumber = 2,
    kPlayerInfoFieldNumber = 10,
    kMonsterInfoFieldNumber = 11,
    kItemInfoFieldNumber = 12,
    kProjectileInfoFieldNumber = 13,
  };
  // .se.common.ObjectId entity_id = 3;
  bool has_entity_id() const;
  private:
  bool _internal_has_entity_id() const;
  public:
  void clear_entity_id();
  const ::se::common::ObjectId& entity_id() const;
  PROTOBUF_NODISCARD ::se::common::ObjectId* release_entity_id();
  ::se::common::ObjectId* mutable_entity_id();
  void set_allocated_entity_id(::se::common::ObjectId* entity_id);
  private:
  const ::se::common::ObjectId& _internal_entity_id() const;
  ::se::common::ObjectId* _internal_mutable_entity_id();
  public:
  void unsafe_arena_set_allocated_entity_id(
      ::se::common::ObjectId* entity_id);
  ::se::common::ObjectId* unsafe_arena_release_entity_id();

  // .se.common.ObjectType type = 1;
  void clear_type();
  ::se::common::ObjectType type() const;
  void set_type(::se::common::ObjectType value);
  private:
  ::se::common::ObjectType _internal_type() const;
  void _internal_set_type(::se::common::ObjectType value);
  public:

  // uint32 template_id = 2;
  void clear_template_id();
  uint32_t template_id() const;
  void set_template_id(uint32_t value);
  private:
  uint32_t _internal_template_id() const;
  void _internal_set_template_id(uint32_t value);
  public:

  // .se.room.PlayerSpawnInfo player_info = 10;
  bool has_player_info() const;
  private:
  bool _internal_has_player_info() const;
  public:
  void clear_player_info();
  const ::se::room::PlayerSpawnInfo& player_info() const;
  PROTOBUF_NODISCARD ::se::room::PlayerSpawnInfo* release_player_info();
  ::se::room::PlayerSpawnInfo* mutable_player_info();
  void set_allocated_player_info(::se::room::PlayerSpawnInfo* player_info);
  private:
  const ::se::room::PlayerSpawnInfo& _internal_player_info() const;
  ::se::room::PlayerSpawnInfo* _internal_mutable_player_info();
  public:
  void unsafe_arena_set_allocated_player_info(
      ::se::room::PlayerSpawnInfo* player_info);
  ::se::room::PlayerSpawnInfo* unsafe_arena_release_player_info();

  // .se.room.MonsterSpawnInfo monster_info = 11;
  bool has_monster_info() const;
  private:
  bool _internal_has_monster_info() const;
  public:
  void clear_monster_info();
  const ::se::room::MonsterSpawnInfo& monster_info() const;
  PROTOBUF_NODISCARD ::se::room::MonsterSpawnInfo* release_monster_info();
  ::se::room::MonsterSpawnInfo* mutable_monster_info();
  void set_allocated_monster_info(::se::room::MonsterSpawnInfo* monster_info);
  private:
  const ::se::room::MonsterSpawnInfo& _internal_monster_info() const;
  ::se::room::MonsterSpawnInfo* _internal_mutable_monster_info();
  public:
  void unsafe_arena_set_allocated_monster_info(
      ::se::room::MonsterSpawnInfo* monster_info);
  ::se::room::MonsterSpawnInfo* unsafe_arena_release_monster_info();

  // .se.room.ItemSpawnInfo item_info = 12;
  bool has_item_info() const;
  private:
  bool _internal_has_item_info() const;
  public:
  void clear_item_info();
  const ::se::room::ItemSpawnInfo& item_info() const;
  PROTOBUF_NODISCARD ::se::room::ItemSpawnInfo* release_item_info();
  ::se::room::ItemSpawnInfo* mutable_item_info();
  void set_allocated_item_info(::se::room::ItemSpawnInfo* item_info);
  private:
  const ::se::room::ItemSpawnInfo& _internal_item_info() const;
  ::se::room::ItemSpawnInfo* _internal_mutable_item_info();
  public:
  void unsafe_arena_set_allocated_item_info(
      ::se::room::ItemSpawnInfo* item_info);
  ::se::room::ItemSpawnInfo* unsafe_arena_release_item_info();

  // .se.room.ProjectileSpawnInfo projectile_info = 13;
  bool has_projectile_info() const;
  private:
  bool _internal_has_projectile_info() const;
  public:
  void clear_projectile_info();
  const ::se::room::ProjectileSpawnInfo& projectile_info() const;
  PROTOBUF_NODISCARD ::se::room::ProjectileSpawnInfo* release_projectile_info();
  ::se::room::ProjectileSpawnInfo* mutable_projectile_info();
  void set_allocated_projectile_info(::se::room::ProjectileSpawnInfo* projectile_info);
  private:
  const ::se::room::ProjectileSpawnInfo& _internal_projectile_info() const;
  ::se::room::ProjectileSpawnInfo* _internal_mutable_projectile_info();
  public:
  void unsafe_arena_set_allocated_projectile_info(
      ::se::room::ProjectileSpawnInfo* projectile_info);
  ::se::room::ProjectileSpawnInfo* unsafe_arena_release_projectile_info();

  void clear_detail();
  DetailCase detail_case() const;
  // @@protoc_insertion_point(class_scope:se.room.SpawnInfo)
 private:
  class _Internal;
  void set_has_player_info();
  void set_has_monster_info();
  void set_has_item_info();
  void set_has_projectile_info();

  inline bool has_detail() const;
  inline void clear_has_detail();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::ObjectId* entity_id_;
    int type_;
    uint32_t template_id_;
    union DetailUnion {
      constexpr DetailUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::se::room::PlayerSpawnInfo* player_info_;
      ::se::room::MonsterSpawnInfo* monster_info_;
      ::se::room::ItemSpawnInfo* item_info_;
      ::se::room::ProjectileSpawnInfo* projectile_info_;
    } detail_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_room_2froom_5ftypes_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoomPlayer

// .se.common.PlayerId player_id = 1;
inline bool RoomPlayer::_internal_has_player_id() const {
  return this != internal_default_instance() && _impl_.player_id_ != nullptr;
}
inline bool RoomPlayer::has_player_id() const {
  return _internal_has_player_id();
}
inline const ::se::common::PlayerId& RoomPlayer::_internal_player_id() const {
  const ::se::common::PlayerId* p = _impl_.player_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::PlayerId&>(
      ::se::common::_PlayerId_default_instance_);
}
inline const ::se::common::PlayerId& RoomPlayer::player_id() const {
  // @@protoc_insertion_point(field_get:se.room.RoomPlayer.player_id)
  return _internal_player_id();
}
inline void RoomPlayer::unsafe_arena_set_allocated_player_id(
    ::se::common::PlayerId* player_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_id_);
  }
  _impl_.player_id_ = player_id;
  if (player_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.RoomPlayer.player_id)
}
inline ::se::common::PlayerId* RoomPlayer::release_player_id() {
  
  ::se::common::PlayerId* temp = _impl_.player_id_;
  _impl_.player_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::PlayerId* RoomPlayer::unsafe_arena_release_player_id() {
  // @@protoc_insertion_point(field_release:se.room.RoomPlayer.player_id)
  
  ::se::common::PlayerId* temp = _impl_.player_id_;
  _impl_.player_id_ = nullptr;
  return temp;
}
inline ::se::common::PlayerId* RoomPlayer::_internal_mutable_player_id() {
  
  if (_impl_.player_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::PlayerId>(GetArenaForAllocation());
    _impl_.player_id_ = p;
  }
  return _impl_.player_id_;
}
inline ::se::common::PlayerId* RoomPlayer::mutable_player_id() {
  ::se::common::PlayerId* _msg = _internal_mutable_player_id();
  // @@protoc_insertion_point(field_mutable:se.room.RoomPlayer.player_id)
  return _msg;
}
inline void RoomPlayer::set_allocated_player_id(::se::common::PlayerId* player_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_id_);
  }
  if (player_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(player_id));
    if (message_arena != submessage_arena) {
      player_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player_id, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.player_id_ = player_id;
  // @@protoc_insertion_point(field_set_allocated:se.room.RoomPlayer.player_id)
}

// .se.common.ObjectId entity_id = 2;
inline bool RoomPlayer::_internal_has_entity_id() const {
  return this != internal_default_instance() && _impl_.entity_id_ != nullptr;
}
inline bool RoomPlayer::has_entity_id() const {
  return _internal_has_entity_id();
}
inline const ::se::common::ObjectId& RoomPlayer::_internal_entity_id() const {
  const ::se::common::ObjectId* p = _impl_.entity_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::ObjectId&>(
      ::se::common::_ObjectId_default_instance_);
}
inline const ::se::common::ObjectId& RoomPlayer::entity_id() const {
  // @@protoc_insertion_point(field_get:se.room.RoomPlayer.entity_id)
  return _internal_entity_id();
}
inline void RoomPlayer::unsafe_arena_set_allocated_entity_id(
    ::se::common::ObjectId* entity_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.entity_id_);
  }
  _impl_.entity_id_ = entity_id;
  if (entity_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.RoomPlayer.entity_id)
}
inline ::se::common::ObjectId* RoomPlayer::release_entity_id() {
  
  ::se::common::ObjectId* temp = _impl_.entity_id_;
  _impl_.entity_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::ObjectId* RoomPlayer::unsafe_arena_release_entity_id() {
  // @@protoc_insertion_point(field_release:se.room.RoomPlayer.entity_id)
  
  ::se::common::ObjectId* temp = _impl_.entity_id_;
  _impl_.entity_id_ = nullptr;
  return temp;
}
inline ::se::common::ObjectId* RoomPlayer::_internal_mutable_entity_id() {
  
  if (_impl_.entity_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::ObjectId>(GetArenaForAllocation());
    _impl_.entity_id_ = p;
  }
  return _impl_.entity_id_;
}
inline ::se::common::ObjectId* RoomPlayer::mutable_entity_id() {
  ::se::common::ObjectId* _msg = _internal_mutable_entity_id();
  // @@protoc_insertion_point(field_mutable:se.room.RoomPlayer.entity_id)
  return _msg;
}
inline void RoomPlayer::set_allocated_entity_id(::se::common::ObjectId* entity_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.entity_id_);
  }
  if (entity_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(entity_id));
    if (message_arena != submessage_arena) {
      entity_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, entity_id, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.entity_id_ = entity_id;
  // @@protoc_insertion_point(field_set_allocated:se.room.RoomPlayer.entity_id)
}

// string nickname = 3;
inline void RoomPlayer::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& RoomPlayer::nickname() const {
  // @@protoc_insertion_point(field_get:se.room.RoomPlayer.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoomPlayer::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:se.room.RoomPlayer.nickname)
}
inline std::string* RoomPlayer::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:se.room.RoomPlayer.nickname)
  return _s;
}
inline const std::string& RoomPlayer::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void RoomPlayer::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* RoomPlayer::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* RoomPlayer::release_nickname() {
  // @@protoc_insertion_point(field_release:se.room.RoomPlayer.nickname)
  return _impl_.nickname_.Release();
}
inline void RoomPlayer::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:se.room.RoomPlayer.nickname)
}

// -------------------------------------------------------------------

// RoomSnapshot

// uint32 room_id = 1;
inline void RoomSnapshot::clear_room_id() {
  _impl_.room_id_ = 0u;
}
inline uint32_t RoomSnapshot::_internal_room_id() const {
  return _impl_.room_id_;
}
inline uint32_t RoomSnapshot::room_id() const {
  // @@protoc_insertion_point(field_get:se.room.RoomSnapshot.room_id)
  return _internal_room_id();
}
inline void RoomSnapshot::_internal_set_room_id(uint32_t value) {
  
  _impl_.room_id_ = value;
}
inline void RoomSnapshot::set_room_id(uint32_t value) {
  _internal_set_room_id(value);
  // @@protoc_insertion_point(field_set:se.room.RoomSnapshot.room_id)
}

// repeated .se.room.RoomPlayer players = 2;
inline int RoomSnapshot::_internal_players_size() const {
  return _impl_.players_.size();
}
inline int RoomSnapshot::players_size() const {
  return _internal_players_size();
}
inline void RoomSnapshot::clear_players() {
  _impl_.players_.Clear();
}
inline ::se::room::RoomPlayer* RoomSnapshot::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:se.room.RoomSnapshot.players)
  return _impl_.players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::se::room::RoomPlayer >*
RoomSnapshot::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:se.room.RoomSnapshot.players)
  return &_impl_.players_;
}
inline const ::se::room::RoomPlayer& RoomSnapshot::_internal_players(int index) const {
  return _impl_.players_.Get(index);
}
inline const ::se::room::RoomPlayer& RoomSnapshot::players(int index) const {
  // @@protoc_insertion_point(field_get:se.room.RoomSnapshot.players)
  return _internal_players(index);
}
inline ::se::room::RoomPlayer* RoomSnapshot::_internal_add_players() {
  return _impl_.players_.Add();
}
inline ::se::room::RoomPlayer* RoomSnapshot::add_players() {
  ::se::room::RoomPlayer* _add = _internal_add_players();
  // @@protoc_insertion_point(field_add:se.room.RoomSnapshot.players)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::se::room::RoomPlayer >&
RoomSnapshot::players() const {
  // @@protoc_insertion_point(field_list:se.room.RoomSnapshot.players)
  return _impl_.players_;
}

// -------------------------------------------------------------------

// PlayerSpawnInfo

// .se.common.MovementState movement = 1;
inline bool PlayerSpawnInfo::_internal_has_movement() const {
  return this != internal_default_instance() && _impl_.movement_ != nullptr;
}
inline bool PlayerSpawnInfo::has_movement() const {
  return _internal_has_movement();
}
inline const ::se::common::MovementState& PlayerSpawnInfo::_internal_movement() const {
  const ::se::common::MovementState* p = _impl_.movement_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::MovementState&>(
      ::se::common::_MovementState_default_instance_);
}
inline const ::se::common::MovementState& PlayerSpawnInfo::movement() const {
  // @@protoc_insertion_point(field_get:se.room.PlayerSpawnInfo.movement)
  return _internal_movement();
}
inline void PlayerSpawnInfo::unsafe_arena_set_allocated_movement(
    ::se::common::MovementState* movement) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movement_);
  }
  _impl_.movement_ = movement;
  if (movement) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.PlayerSpawnInfo.movement)
}
inline ::se::common::MovementState* PlayerSpawnInfo::release_movement() {
  
  ::se::common::MovementState* temp = _impl_.movement_;
  _impl_.movement_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::MovementState* PlayerSpawnInfo::unsafe_arena_release_movement() {
  // @@protoc_insertion_point(field_release:se.room.PlayerSpawnInfo.movement)
  
  ::se::common::MovementState* temp = _impl_.movement_;
  _impl_.movement_ = nullptr;
  return temp;
}
inline ::se::common::MovementState* PlayerSpawnInfo::_internal_mutable_movement() {
  
  if (_impl_.movement_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::MovementState>(GetArenaForAllocation());
    _impl_.movement_ = p;
  }
  return _impl_.movement_;
}
inline ::se::common::MovementState* PlayerSpawnInfo::mutable_movement() {
  ::se::common::MovementState* _msg = _internal_mutable_movement();
  // @@protoc_insertion_point(field_mutable:se.room.PlayerSpawnInfo.movement)
  return _msg;
}
inline void PlayerSpawnInfo::set_allocated_movement(::se::common::MovementState* movement) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movement_);
  }
  if (movement) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(movement));
    if (message_arena != submessage_arena) {
      movement = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, movement, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.movement_ = movement;
  // @@protoc_insertion_point(field_set_allocated:se.room.PlayerSpawnInfo.movement)
}

// -------------------------------------------------------------------

// MonsterSpawnInfo

// .se.common.MovementState movement = 1;
inline bool MonsterSpawnInfo::_internal_has_movement() const {
  return this != internal_default_instance() && _impl_.movement_ != nullptr;
}
inline bool MonsterSpawnInfo::has_movement() const {
  return _internal_has_movement();
}
inline const ::se::common::MovementState& MonsterSpawnInfo::_internal_movement() const {
  const ::se::common::MovementState* p = _impl_.movement_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::MovementState&>(
      ::se::common::_MovementState_default_instance_);
}
inline const ::se::common::MovementState& MonsterSpawnInfo::movement() const {
  // @@protoc_insertion_point(field_get:se.room.MonsterSpawnInfo.movement)
  return _internal_movement();
}
inline void MonsterSpawnInfo::unsafe_arena_set_allocated_movement(
    ::se::common::MovementState* movement) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movement_);
  }
  _impl_.movement_ = movement;
  if (movement) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.MonsterSpawnInfo.movement)
}
inline ::se::common::MovementState* MonsterSpawnInfo::release_movement() {
  
  ::se::common::MovementState* temp = _impl_.movement_;
  _impl_.movement_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::MovementState* MonsterSpawnInfo::unsafe_arena_release_movement() {
  // @@protoc_insertion_point(field_release:se.room.MonsterSpawnInfo.movement)
  
  ::se::common::MovementState* temp = _impl_.movement_;
  _impl_.movement_ = nullptr;
  return temp;
}
inline ::se::common::MovementState* MonsterSpawnInfo::_internal_mutable_movement() {
  
  if (_impl_.movement_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::MovementState>(GetArenaForAllocation());
    _impl_.movement_ = p;
  }
  return _impl_.movement_;
}
inline ::se::common::MovementState* MonsterSpawnInfo::mutable_movement() {
  ::se::common::MovementState* _msg = _internal_mutable_movement();
  // @@protoc_insertion_point(field_mutable:se.room.MonsterSpawnInfo.movement)
  return _msg;
}
inline void MonsterSpawnInfo::set_allocated_movement(::se::common::MovementState* movement) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movement_);
  }
  if (movement) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(movement));
    if (message_arena != submessage_arena) {
      movement = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, movement, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.movement_ = movement;
  // @@protoc_insertion_point(field_set_allocated:se.room.MonsterSpawnInfo.movement)
}

// -------------------------------------------------------------------

// ItemSpawnInfo

// .se.common.Vector3 position = 1;
inline bool ItemSpawnInfo::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool ItemSpawnInfo::has_position() const {
  return _internal_has_position();
}
inline const ::se::common::Vector3& ItemSpawnInfo::_internal_position() const {
  const ::se::common::Vector3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& ItemSpawnInfo::position() const {
  // @@protoc_insertion_point(field_get:se.room.ItemSpawnInfo.position)
  return _internal_position();
}
inline void ItemSpawnInfo::unsafe_arena_set_allocated_position(
    ::se::common::Vector3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.ItemSpawnInfo.position)
}
inline ::se::common::Vector3* ItemSpawnInfo::release_position() {
  
  ::se::common::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* ItemSpawnInfo::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:se.room.ItemSpawnInfo.position)
  
  ::se::common::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* ItemSpawnInfo::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::se::common::Vector3* ItemSpawnInfo::mutable_position() {
  ::se::common::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:se.room.ItemSpawnInfo.position)
  return _msg;
}
inline void ItemSpawnInfo::set_allocated_position(::se::common::Vector3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:se.room.ItemSpawnInfo.position)
}

// .se.common.Vector3 velocity = 2;
inline bool ItemSpawnInfo::_internal_has_velocity() const {
  return this != internal_default_instance() && _impl_.velocity_ != nullptr;
}
inline bool ItemSpawnInfo::has_velocity() const {
  return _internal_has_velocity();
}
inline const ::se::common::Vector3& ItemSpawnInfo::_internal_velocity() const {
  const ::se::common::Vector3* p = _impl_.velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& ItemSpawnInfo::velocity() const {
  // @@protoc_insertion_point(field_get:se.room.ItemSpawnInfo.velocity)
  return _internal_velocity();
}
inline void ItemSpawnInfo::unsafe_arena_set_allocated_velocity(
    ::se::common::Vector3* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  _impl_.velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.ItemSpawnInfo.velocity)
}
inline ::se::common::Vector3* ItemSpawnInfo::release_velocity() {
  
  ::se::common::Vector3* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* ItemSpawnInfo::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:se.room.ItemSpawnInfo.velocity)
  
  ::se::common::Vector3* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* ItemSpawnInfo::_internal_mutable_velocity() {
  
  if (_impl_.velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.velocity_ = p;
  }
  return _impl_.velocity_;
}
inline ::se::common::Vector3* ItemSpawnInfo::mutable_velocity() {
  ::se::common::Vector3* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:se.room.ItemSpawnInfo.velocity)
  return _msg;
}
inline void ItemSpawnInfo::set_allocated_velocity(::se::common::Vector3* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity));
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:se.room.ItemSpawnInfo.velocity)
}

// uint32 amount = 3;
inline void ItemSpawnInfo::clear_amount() {
  _impl_.amount_ = 0u;
}
inline uint32_t ItemSpawnInfo::_internal_amount() const {
  return _impl_.amount_;
}
inline uint32_t ItemSpawnInfo::amount() const {
  // @@protoc_insertion_point(field_get:se.room.ItemSpawnInfo.amount)
  return _internal_amount();
}
inline void ItemSpawnInfo::_internal_set_amount(uint32_t value) {
  
  _impl_.amount_ = value;
}
inline void ItemSpawnInfo::set_amount(uint32_t value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:se.room.ItemSpawnInfo.amount)
}

// -------------------------------------------------------------------

// ProjectileSpawnInfo

// .se.common.Vector3 position = 1;
inline bool ProjectileSpawnInfo::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool ProjectileSpawnInfo::has_position() const {
  return _internal_has_position();
}
inline const ::se::common::Vector3& ProjectileSpawnInfo::_internal_position() const {
  const ::se::common::Vector3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& ProjectileSpawnInfo::position() const {
  // @@protoc_insertion_point(field_get:se.room.ProjectileSpawnInfo.position)
  return _internal_position();
}
inline void ProjectileSpawnInfo::unsafe_arena_set_allocated_position(
    ::se::common::Vector3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.ProjectileSpawnInfo.position)
}
inline ::se::common::Vector3* ProjectileSpawnInfo::release_position() {
  
  ::se::common::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* ProjectileSpawnInfo::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:se.room.ProjectileSpawnInfo.position)
  
  ::se::common::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* ProjectileSpawnInfo::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::se::common::Vector3* ProjectileSpawnInfo::mutable_position() {
  ::se::common::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:se.room.ProjectileSpawnInfo.position)
  return _msg;
}
inline void ProjectileSpawnInfo::set_allocated_position(::se::common::Vector3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:se.room.ProjectileSpawnInfo.position)
}

// .se.common.Vector3 velocity = 2;
inline bool ProjectileSpawnInfo::_internal_has_velocity() const {
  return this != internal_default_instance() && _impl_.velocity_ != nullptr;
}
inline bool ProjectileSpawnInfo::has_velocity() const {
  return _internal_has_velocity();
}
inline const ::se::common::Vector3& ProjectileSpawnInfo::_internal_velocity() const {
  const ::se::common::Vector3* p = _impl_.velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& ProjectileSpawnInfo::velocity() const {
  // @@protoc_insertion_point(field_get:se.room.ProjectileSpawnInfo.velocity)
  return _internal_velocity();
}
inline void ProjectileSpawnInfo::unsafe_arena_set_allocated_velocity(
    ::se::common::Vector3* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  _impl_.velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.ProjectileSpawnInfo.velocity)
}
inline ::se::common::Vector3* ProjectileSpawnInfo::release_velocity() {
  
  ::se::common::Vector3* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* ProjectileSpawnInfo::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:se.room.ProjectileSpawnInfo.velocity)
  
  ::se::common::Vector3* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* ProjectileSpawnInfo::_internal_mutable_velocity() {
  
  if (_impl_.velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.velocity_ = p;
  }
  return _impl_.velocity_;
}
inline ::se::common::Vector3* ProjectileSpawnInfo::mutable_velocity() {
  ::se::common::Vector3* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:se.room.ProjectileSpawnInfo.velocity)
  return _msg;
}
inline void ProjectileSpawnInfo::set_allocated_velocity(::se::common::Vector3* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity));
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:se.room.ProjectileSpawnInfo.velocity)
}

// -------------------------------------------------------------------

// SpawnInfo

// .se.common.ObjectType type = 1;
inline void SpawnInfo::clear_type() {
  _impl_.type_ = 0;
}
inline ::se::common::ObjectType SpawnInfo::_internal_type() const {
  return static_cast< ::se::common::ObjectType >(_impl_.type_);
}
inline ::se::common::ObjectType SpawnInfo::type() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.type)
  return _internal_type();
}
inline void SpawnInfo::_internal_set_type(::se::common::ObjectType value) {
  
  _impl_.type_ = value;
}
inline void SpawnInfo::set_type(::se::common::ObjectType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:se.room.SpawnInfo.type)
}

// uint32 template_id = 2;
inline void SpawnInfo::clear_template_id() {
  _impl_.template_id_ = 0u;
}
inline uint32_t SpawnInfo::_internal_template_id() const {
  return _impl_.template_id_;
}
inline uint32_t SpawnInfo::template_id() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.template_id)
  return _internal_template_id();
}
inline void SpawnInfo::_internal_set_template_id(uint32_t value) {
  
  _impl_.template_id_ = value;
}
inline void SpawnInfo::set_template_id(uint32_t value) {
  _internal_set_template_id(value);
  // @@protoc_insertion_point(field_set:se.room.SpawnInfo.template_id)
}

// .se.common.ObjectId entity_id = 3;
inline bool SpawnInfo::_internal_has_entity_id() const {
  return this != internal_default_instance() && _impl_.entity_id_ != nullptr;
}
inline bool SpawnInfo::has_entity_id() const {
  return _internal_has_entity_id();
}
inline const ::se::common::ObjectId& SpawnInfo::_internal_entity_id() const {
  const ::se::common::ObjectId* p = _impl_.entity_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::ObjectId&>(
      ::se::common::_ObjectId_default_instance_);
}
inline const ::se::common::ObjectId& SpawnInfo::entity_id() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.entity_id)
  return _internal_entity_id();
}
inline void SpawnInfo::unsafe_arena_set_allocated_entity_id(
    ::se::common::ObjectId* entity_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.entity_id_);
  }
  _impl_.entity_id_ = entity_id;
  if (entity_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.SpawnInfo.entity_id)
}
inline ::se::common::ObjectId* SpawnInfo::release_entity_id() {
  
  ::se::common::ObjectId* temp = _impl_.entity_id_;
  _impl_.entity_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::ObjectId* SpawnInfo::unsafe_arena_release_entity_id() {
  // @@protoc_insertion_point(field_release:se.room.SpawnInfo.entity_id)
  
  ::se::common::ObjectId* temp = _impl_.entity_id_;
  _impl_.entity_id_ = nullptr;
  return temp;
}
inline ::se::common::ObjectId* SpawnInfo::_internal_mutable_entity_id() {
  
  if (_impl_.entity_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::ObjectId>(GetArenaForAllocation());
    _impl_.entity_id_ = p;
  }
  return _impl_.entity_id_;
}
inline ::se::common::ObjectId* SpawnInfo::mutable_entity_id() {
  ::se::common::ObjectId* _msg = _internal_mutable_entity_id();
  // @@protoc_insertion_point(field_mutable:se.room.SpawnInfo.entity_id)
  return _msg;
}
inline void SpawnInfo::set_allocated_entity_id(::se::common::ObjectId* entity_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.entity_id_);
  }
  if (entity_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(entity_id));
    if (message_arena != submessage_arena) {
      entity_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, entity_id, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.entity_id_ = entity_id;
  // @@protoc_insertion_point(field_set_allocated:se.room.SpawnInfo.entity_id)
}

// .se.room.PlayerSpawnInfo player_info = 10;
inline bool SpawnInfo::_internal_has_player_info() const {
  return detail_case() == kPlayerInfo;
}
inline bool SpawnInfo::has_player_info() const {
  return _internal_has_player_info();
}
inline void SpawnInfo::set_has_player_info() {
  _impl_._oneof_case_[0] = kPlayerInfo;
}
inline void SpawnInfo::clear_player_info() {
  if (_internal_has_player_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.detail_.player_info_;
    }
    clear_has_detail();
  }
}
inline ::se::room::PlayerSpawnInfo* SpawnInfo::release_player_info() {
  // @@protoc_insertion_point(field_release:se.room.SpawnInfo.player_info)
  if (_internal_has_player_info()) {
    clear_has_detail();
    ::se::room::PlayerSpawnInfo* temp = _impl_.detail_.player_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.detail_.player_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::se::room::PlayerSpawnInfo& SpawnInfo::_internal_player_info() const {
  return _internal_has_player_info()
      ? *_impl_.detail_.player_info_
      : reinterpret_cast< ::se::room::PlayerSpawnInfo&>(::se::room::_PlayerSpawnInfo_default_instance_);
}
inline const ::se::room::PlayerSpawnInfo& SpawnInfo::player_info() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.player_info)
  return _internal_player_info();
}
inline ::se::room::PlayerSpawnInfo* SpawnInfo::unsafe_arena_release_player_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:se.room.SpawnInfo.player_info)
  if (_internal_has_player_info()) {
    clear_has_detail();
    ::se::room::PlayerSpawnInfo* temp = _impl_.detail_.player_info_;
    _impl_.detail_.player_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SpawnInfo::unsafe_arena_set_allocated_player_info(::se::room::PlayerSpawnInfo* player_info) {
  clear_detail();
  if (player_info) {
    set_has_player_info();
    _impl_.detail_.player_info_ = player_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.SpawnInfo.player_info)
}
inline ::se::room::PlayerSpawnInfo* SpawnInfo::_internal_mutable_player_info() {
  if (!_internal_has_player_info()) {
    clear_detail();
    set_has_player_info();
    _impl_.detail_.player_info_ = CreateMaybeMessage< ::se::room::PlayerSpawnInfo >(GetArenaForAllocation());
  }
  return _impl_.detail_.player_info_;
}
inline ::se::room::PlayerSpawnInfo* SpawnInfo::mutable_player_info() {
  ::se::room::PlayerSpawnInfo* _msg = _internal_mutable_player_info();
  // @@protoc_insertion_point(field_mutable:se.room.SpawnInfo.player_info)
  return _msg;
}

// .se.room.MonsterSpawnInfo monster_info = 11;
inline bool SpawnInfo::_internal_has_monster_info() const {
  return detail_case() == kMonsterInfo;
}
inline bool SpawnInfo::has_monster_info() const {
  return _internal_has_monster_info();
}
inline void SpawnInfo::set_has_monster_info() {
  _impl_._oneof_case_[0] = kMonsterInfo;
}
inline void SpawnInfo::clear_monster_info() {
  if (_internal_has_monster_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.detail_.monster_info_;
    }
    clear_has_detail();
  }
}
inline ::se::room::MonsterSpawnInfo* SpawnInfo::release_monster_info() {
  // @@protoc_insertion_point(field_release:se.room.SpawnInfo.monster_info)
  if (_internal_has_monster_info()) {
    clear_has_detail();
    ::se::room::MonsterSpawnInfo* temp = _impl_.detail_.monster_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.detail_.monster_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::se::room::MonsterSpawnInfo& SpawnInfo::_internal_monster_info() const {
  return _internal_has_monster_info()
      ? *_impl_.detail_.monster_info_
      : reinterpret_cast< ::se::room::MonsterSpawnInfo&>(::se::room::_MonsterSpawnInfo_default_instance_);
}
inline const ::se::room::MonsterSpawnInfo& SpawnInfo::monster_info() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.monster_info)
  return _internal_monster_info();
}
inline ::se::room::MonsterSpawnInfo* SpawnInfo::unsafe_arena_release_monster_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:se.room.SpawnInfo.monster_info)
  if (_internal_has_monster_info()) {
    clear_has_detail();
    ::se::room::MonsterSpawnInfo* temp = _impl_.detail_.monster_info_;
    _impl_.detail_.monster_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SpawnInfo::unsafe_arena_set_allocated_monster_info(::se::room::MonsterSpawnInfo* monster_info) {
  clear_detail();
  if (monster_info) {
    set_has_monster_info();
    _impl_.detail_.monster_info_ = monster_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.SpawnInfo.monster_info)
}
inline ::se::room::MonsterSpawnInfo* SpawnInfo::_internal_mutable_monster_info() {
  if (!_internal_has_monster_info()) {
    clear_detail();
    set_has_monster_info();
    _impl_.detail_.monster_info_ = CreateMaybeMessage< ::se::room::MonsterSpawnInfo >(GetArenaForAllocation());
  }
  return _impl_.detail_.monster_info_;
}
inline ::se::room::MonsterSpawnInfo* SpawnInfo::mutable_monster_info() {
  ::se::room::MonsterSpawnInfo* _msg = _internal_mutable_monster_info();
  // @@protoc_insertion_point(field_mutable:se.room.SpawnInfo.monster_info)
  return _msg;
}

// .se.room.ItemSpawnInfo item_info = 12;
inline bool SpawnInfo::_internal_has_item_info() const {
  return detail_case() == kItemInfo;
}
inline bool SpawnInfo::has_item_info() const {
  return _internal_has_item_info();
}
inline void SpawnInfo::set_has_item_info() {
  _impl_._oneof_case_[0] = kItemInfo;
}
inline void SpawnInfo::clear_item_info() {
  if (_internal_has_item_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.detail_.item_info_;
    }
    clear_has_detail();
  }
}
inline ::se::room::ItemSpawnInfo* SpawnInfo::release_item_info() {
  // @@protoc_insertion_point(field_release:se.room.SpawnInfo.item_info)
  if (_internal_has_item_info()) {
    clear_has_detail();
    ::se::room::ItemSpawnInfo* temp = _impl_.detail_.item_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.detail_.item_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::se::room::ItemSpawnInfo& SpawnInfo::_internal_item_info() const {
  return _internal_has_item_info()
      ? *_impl_.detail_.item_info_
      : reinterpret_cast< ::se::room::ItemSpawnInfo&>(::se::room::_ItemSpawnInfo_default_instance_);
}
inline const ::se::room::ItemSpawnInfo& SpawnInfo::item_info() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.item_info)
  return _internal_item_info();
}
inline ::se::room::ItemSpawnInfo* SpawnInfo::unsafe_arena_release_item_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:se.room.SpawnInfo.item_info)
  if (_internal_has_item_info()) {
    clear_has_detail();
    ::se::room::ItemSpawnInfo* temp = _impl_.detail_.item_info_;
    _impl_.detail_.item_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SpawnInfo::unsafe_arena_set_allocated_item_info(::se::room::ItemSpawnInfo* item_info) {
  clear_detail();
  if (item_info) {
    set_has_item_info();
    _impl_.detail_.item_info_ = item_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.SpawnInfo.item_info)
}
inline ::se::room::ItemSpawnInfo* SpawnInfo::_internal_mutable_item_info() {
  if (!_internal_has_item_info()) {
    clear_detail();
    set_has_item_info();
    _impl_.detail_.item_info_ = CreateMaybeMessage< ::se::room::ItemSpawnInfo >(GetArenaForAllocation());
  }
  return _impl_.detail_.item_info_;
}
inline ::se::room::ItemSpawnInfo* SpawnInfo::mutable_item_info() {
  ::se::room::ItemSpawnInfo* _msg = _internal_mutable_item_info();
  // @@protoc_insertion_point(field_mutable:se.room.SpawnInfo.item_info)
  return _msg;
}

// .se.room.ProjectileSpawnInfo projectile_info = 13;
inline bool SpawnInfo::_internal_has_projectile_info() const {
  return detail_case() == kProjectileInfo;
}
inline bool SpawnInfo::has_projectile_info() const {
  return _internal_has_projectile_info();
}
inline void SpawnInfo::set_has_projectile_info() {
  _impl_._oneof_case_[0] = kProjectileInfo;
}
inline void SpawnInfo::clear_projectile_info() {
  if (_internal_has_projectile_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.detail_.projectile_info_;
    }
    clear_has_detail();
  }
}
inline ::se::room::ProjectileSpawnInfo* SpawnInfo::release_projectile_info() {
  // @@protoc_insertion_point(field_release:se.room.SpawnInfo.projectile_info)
  if (_internal_has_projectile_info()) {
    clear_has_detail();
    ::se::room::ProjectileSpawnInfo* temp = _impl_.detail_.projectile_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.detail_.projectile_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::se::room::ProjectileSpawnInfo& SpawnInfo::_internal_projectile_info() const {
  return _internal_has_projectile_info()
      ? *_impl_.detail_.projectile_info_
      : reinterpret_cast< ::se::room::ProjectileSpawnInfo&>(::se::room::_ProjectileSpawnInfo_default_instance_);
}
inline const ::se::room::ProjectileSpawnInfo& SpawnInfo::projectile_info() const {
  // @@protoc_insertion_point(field_get:se.room.SpawnInfo.projectile_info)
  return _internal_projectile_info();
}
inline ::se::room::ProjectileSpawnInfo* SpawnInfo::unsafe_arena_release_projectile_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:se.room.SpawnInfo.projectile_info)
  if (_internal_has_projectile_info()) {
    clear_has_detail();
    ::se::room::ProjectileSpawnInfo* temp = _impl_.detail_.projectile_info_;
    _impl_.detail_.projectile_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SpawnInfo::unsafe_arena_set_allocated_projectile_info(::se::room::ProjectileSpawnInfo* projectile_info) {
  clear_detail();
  if (projectile_info) {
    set_has_projectile_info();
    _impl_.detail_.projectile_info_ = projectile_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.room.SpawnInfo.projectile_info)
}
inline ::se::room::ProjectileSpawnInfo* SpawnInfo::_internal_mutable_projectile_info() {
  if (!_internal_has_projectile_info()) {
    clear_detail();
    set_has_projectile_info();
    _impl_.detail_.projectile_info_ = CreateMaybeMessage< ::se::room::ProjectileSpawnInfo >(GetArenaForAllocation());
  }
  return _impl_.detail_.projectile_info_;
}
inline ::se::room::ProjectileSpawnInfo* SpawnInfo::mutable_projectile_info() {
  ::se::room::ProjectileSpawnInfo* _msg = _internal_mutable_projectile_info();
  // @@protoc_insertion_point(field_mutable:se.room.SpawnInfo.projectile_info)
  return _msg;
}

inline bool SpawnInfo::has_detail() const {
  return detail_case() != DETAIL_NOT_SET;
}
inline void SpawnInfo::clear_has_detail() {
  _impl_._oneof_case_[0] = DETAIL_NOT_SET;
}
inline SpawnInfo::DetailCase SpawnInfo::detail_case() const {
  return SpawnInfo::DetailCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace room
}  // namespace se

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_room_2froom_5ftypes_2eproto
