// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room/room_messages.proto

#include "room/room_messages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace se {
namespace room {
PROTOBUF_CONSTEXPR C_RoomReadyReq::C_RoomReadyReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ready_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_RoomReadyReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_RoomReadyReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_RoomReadyReqDefaultTypeInternal() {}
  union {
    C_RoomReadyReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_RoomReadyReqDefaultTypeInternal _C_RoomReadyReq_default_instance_;
PROTOBUF_CONSTEXPR N_RoomReadyChanged::N_RoomReadyChanged(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_id_)*/nullptr
  , /*decltype(_impl_.ready_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct N_RoomReadyChangedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR N_RoomReadyChangedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~N_RoomReadyChangedDefaultTypeInternal() {}
  union {
    N_RoomReadyChanged _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 N_RoomReadyChangedDefaultTypeInternal _N_RoomReadyChanged_default_instance_;
PROTOBUF_CONSTEXPR N_GameStart::N_GameStart(
    ::_pbi::ConstantInitialized) {}
struct N_GameStartDefaultTypeInternal {
  PROTOBUF_CONSTEXPR N_GameStartDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~N_GameStartDefaultTypeInternal() {}
  union {
    N_GameStart _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 N_GameStartDefaultTypeInternal _N_GameStart_default_instance_;
PROTOBUF_CONSTEXPR C_MoveInput::C_MoveInput(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.move_x_)*/0
  , /*decltype(_impl_.move_y_)*/0
  , /*decltype(_impl_.yaw_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_MoveInputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_MoveInputDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_MoveInputDefaultTypeInternal() {}
  union {
    C_MoveInput _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_MoveInputDefaultTypeInternal _C_MoveInput_default_instance_;
PROTOBUF_CONSTEXPR C_AimInput::C_AimInput(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pitch_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_AimInputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_AimInputDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_AimInputDefaultTypeInternal() {}
  union {
    C_AimInput _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_AimInputDefaultTypeInternal _C_AimInput_default_instance_;
PROTOBUF_CONSTEXPR C_FireReq::C_FireReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.weapon_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_FireReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_FireReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_FireReqDefaultTypeInternal() {}
  union {
    C_FireReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_FireReqDefaultTypeInternal _C_FireReq_default_instance_;
PROTOBUF_CONSTEXPR S_EntityState::S_EntityState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entities_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_EntityStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_EntityStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_EntityStateDefaultTypeInternal() {}
  union {
    S_EntityState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_EntityStateDefaultTypeInternal _S_EntityState_default_instance_;
PROTOBUF_CONSTEXPR N_EntitySpawn::N_EntitySpawn(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct N_EntitySpawnDefaultTypeInternal {
  PROTOBUF_CONSTEXPR N_EntitySpawnDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~N_EntitySpawnDefaultTypeInternal() {}
  union {
    N_EntitySpawn _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 N_EntitySpawnDefaultTypeInternal _N_EntitySpawn_default_instance_;
PROTOBUF_CONSTEXPR N_EntityDespawn::N_EntityDespawn(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_id_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct N_EntityDespawnDefaultTypeInternal {
  PROTOBUF_CONSTEXPR N_EntityDespawnDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~N_EntityDespawnDefaultTypeInternal() {}
  union {
    N_EntityDespawn _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 N_EntityDespawnDefaultTypeInternal _N_EntityDespawn_default_instance_;
PROTOBUF_CONSTEXPR N_HitEvent::N_HitEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.attacker_)*/nullptr
  , /*decltype(_impl_.victim_)*/nullptr
  , /*decltype(_impl_.damage_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct N_HitEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR N_HitEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~N_HitEventDefaultTypeInternal() {}
  union {
    N_HitEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 N_HitEventDefaultTypeInternal _N_HitEvent_default_instance_;
}  // namespace room
}  // namespace se
static ::_pb::Metadata file_level_metadata_room_2froom_5fmessages_2eproto[10];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_room_2froom_5fmessages_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_room_2froom_5fmessages_2eproto = nullptr;

const uint32_t TableStruct_room_2froom_5fmessages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::C_RoomReadyReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::C_RoomReadyReq, _impl_.ready_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::N_RoomReadyChanged, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::N_RoomReadyChanged, _impl_.entity_id_),
  PROTOBUF_FIELD_OFFSET(::se::room::N_RoomReadyChanged, _impl_.ready_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::N_GameStart, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::C_MoveInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::C_MoveInput, _impl_.move_x_),
  PROTOBUF_FIELD_OFFSET(::se::room::C_MoveInput, _impl_.move_y_),
  PROTOBUF_FIELD_OFFSET(::se::room::C_MoveInput, _impl_.yaw_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::C_AimInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::C_AimInput, _impl_.pitch_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::C_FireReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::C_FireReq, _impl_.weapon_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::S_EntityState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::S_EntityState, _impl_.entities_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::N_EntitySpawn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::N_EntitySpawn, _impl_.entity_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::N_EntityDespawn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::N_EntityDespawn, _impl_.entity_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::N_HitEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::N_HitEvent, _impl_.attacker_),
  PROTOBUF_FIELD_OFFSET(::se::room::N_HitEvent, _impl_.victim_),
  PROTOBUF_FIELD_OFFSET(::se::room::N_HitEvent, _impl_.damage_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::se::room::C_RoomReadyReq)},
  { 7, -1, -1, sizeof(::se::room::N_RoomReadyChanged)},
  { 15, -1, -1, sizeof(::se::room::N_GameStart)},
  { 21, -1, -1, sizeof(::se::room::C_MoveInput)},
  { 30, -1, -1, sizeof(::se::room::C_AimInput)},
  { 37, -1, -1, sizeof(::se::room::C_FireReq)},
  { 44, -1, -1, sizeof(::se::room::S_EntityState)},
  { 51, -1, -1, sizeof(::se::room::N_EntitySpawn)},
  { 58, -1, -1, sizeof(::se::room::N_EntityDespawn)},
  { 65, -1, -1, sizeof(::se::room::N_HitEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::se::room::_C_RoomReadyReq_default_instance_._instance,
  &::se::room::_N_RoomReadyChanged_default_instance_._instance,
  &::se::room::_N_GameStart_default_instance_._instance,
  &::se::room::_C_MoveInput_default_instance_._instance,
  &::se::room::_C_AimInput_default_instance_._instance,
  &::se::room::_C_FireReq_default_instance_._instance,
  &::se::room::_S_EntityState_default_instance_._instance,
  &::se::room::_N_EntitySpawn_default_instance_._instance,
  &::se::room::_N_EntityDespawn_default_instance_._instance,
  &::se::room::_N_HitEvent_default_instance_._instance,
};

const char descriptor_table_protodef_room_2froom_5fmessages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030room/room_messages.proto\022\007se.room\032\034opt"
  "ions/packet_options.proto\032\031common/common"
  "_types.proto\032\025room/room_types.proto\".\n\016C"
  "_RoomReadyReq\022\r\n\005ready\030\001 \001(\010:\r\210\265\030\302\027\220\265\030\001\230"
  "\265\030\003\"Z\n\022N_RoomReadyChanged\022&\n\tentity_id\030\001"
  " \001(\0132\023.se.common.EntityId\022\r\n\005ready\030\002 \001(\010"
  ":\r\210\265\030\303\027\220\265\030\002\230\265\030\003\"\034\n\013N_GameStart:\r\210\265\030\314\027\220\265\030"
  "\002\230\265\030\003\"I\n\013C_MoveInput\022\016\n\006move_x\030\001 \001(\002\022\016\n\006"
  "move_y\030\002 \001(\002\022\013\n\003yaw\030\003 \001(\002:\r\210\265\030\234\030\220\265\030\001\230\265\030\003"
  "\"*\n\nC_AimInput\022\r\n\005pitch\030\001 \001(\002:\r\210\265\030\235\030\220\265\030\001"
  "\230\265\030\003\"-\n\tC_FireReq\022\021\n\tweapon_id\030\001 \001(\r:\r\210\265"
  "\030\246\030\220\265\030\001\230\265\030\003\"F\n\rS_EntityState\022&\n\010entities"
  "\030\001 \003(\0132\024.se.room.EntityState:\r\210\265\030\200\031\220\265\030\002\230"
  "\265\030\003\"D\n\rN_EntitySpawn\022$\n\006entity\030\001 \001(\0132\024.s"
  "e.room.EntityState:\r\210\265\030\212\031\220\265\030\002\230\265\030\003\"H\n\017N_E"
  "ntityDespawn\022&\n\tentity_id\030\001 \001(\0132\023.se.com"
  "mon.EntityId:\r\210\265\030\213\031\220\265\030\002\230\265\030\003\"w\n\nN_HitEven"
  "t\022%\n\010attacker\030\001 \001(\0132\023.se.common.EntityId"
  "\022#\n\006victim\030\002 \001(\0132\023.se.common.EntityId\022\016\n"
  "\006damage\030\003 \001(\r:\r\210\265\030\224\031\220\265\030\002\230\265\030\003b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_room_2froom_5fmessages_2eproto_deps[3] = {
  &::descriptor_table_common_2fcommon_5ftypes_2eproto,
  &::descriptor_table_options_2fpacket_5foptions_2eproto,
  &::descriptor_table_room_2froom_5ftypes_2eproto,
};
static ::_pbi::once_flag descriptor_table_room_2froom_5fmessages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_room_2froom_5fmessages_2eproto = {
    false, false, 796, descriptor_table_protodef_room_2froom_5fmessages_2eproto,
    "room/room_messages.proto",
    &descriptor_table_room_2froom_5fmessages_2eproto_once, descriptor_table_room_2froom_5fmessages_2eproto_deps, 3, 10,
    schemas, file_default_instances, TableStruct_room_2froom_5fmessages_2eproto::offsets,
    file_level_metadata_room_2froom_5fmessages_2eproto, file_level_enum_descriptors_room_2froom_5fmessages_2eproto,
    file_level_service_descriptors_room_2froom_5fmessages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_room_2froom_5fmessages_2eproto_getter() {
  return &descriptor_table_room_2froom_5fmessages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_room_2froom_5fmessages_2eproto(&descriptor_table_room_2froom_5fmessages_2eproto);
namespace se {
namespace room {

// ===================================================================

class C_RoomReadyReq::_Internal {
 public:
};

C_RoomReadyReq::C_RoomReadyReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.C_RoomReadyReq)
}
C_RoomReadyReq::C_RoomReadyReq(const C_RoomReadyReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_RoomReadyReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ready_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.ready_ = from._impl_.ready_;
  // @@protoc_insertion_point(copy_constructor:se.room.C_RoomReadyReq)
}

inline void C_RoomReadyReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ready_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C_RoomReadyReq::~C_RoomReadyReq() {
  // @@protoc_insertion_point(destructor:se.room.C_RoomReadyReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_RoomReadyReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C_RoomReadyReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_RoomReadyReq::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.C_RoomReadyReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ready_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_RoomReadyReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool ready = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ready_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_RoomReadyReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.C_RoomReadyReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ready = 1;
  if (this->_internal_ready() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_ready(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.C_RoomReadyReq)
  return target;
}

size_t C_RoomReadyReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.C_RoomReadyReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ready = 1;
  if (this->_internal_ready() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_RoomReadyReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_RoomReadyReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_RoomReadyReq::GetClassData() const { return &_class_data_; }


void C_RoomReadyReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_RoomReadyReq*>(&to_msg);
  auto& from = static_cast<const C_RoomReadyReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.C_RoomReadyReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ready() != 0) {
    _this->_internal_set_ready(from._internal_ready());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_RoomReadyReq::CopyFrom(const C_RoomReadyReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.C_RoomReadyReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_RoomReadyReq::IsInitialized() const {
  return true;
}

void C_RoomReadyReq::InternalSwap(C_RoomReadyReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.ready_, other->_impl_.ready_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C_RoomReadyReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[0]);
}

// ===================================================================

class N_RoomReadyChanged::_Internal {
 public:
  static const ::se::common::EntityId& entity_id(const N_RoomReadyChanged* msg);
};

const ::se::common::EntityId&
N_RoomReadyChanged::_Internal::entity_id(const N_RoomReadyChanged* msg) {
  return *msg->_impl_.entity_id_;
}
void N_RoomReadyChanged::clear_entity_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
}
N_RoomReadyChanged::N_RoomReadyChanged(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.N_RoomReadyChanged)
}
N_RoomReadyChanged::N_RoomReadyChanged(const N_RoomReadyChanged& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  N_RoomReadyChanged* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){nullptr}
    , decltype(_impl_.ready_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_entity_id()) {
    _this->_impl_.entity_id_ = new ::se::common::EntityId(*from._impl_.entity_id_);
  }
  _this->_impl_.ready_ = from._impl_.ready_;
  // @@protoc_insertion_point(copy_constructor:se.room.N_RoomReadyChanged)
}

inline void N_RoomReadyChanged::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){nullptr}
    , decltype(_impl_.ready_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

N_RoomReadyChanged::~N_RoomReadyChanged() {
  // @@protoc_insertion_point(destructor:se.room.N_RoomReadyChanged)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void N_RoomReadyChanged::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.entity_id_;
}

void N_RoomReadyChanged::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void N_RoomReadyChanged::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.N_RoomReadyChanged)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
  _impl_.ready_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* N_RoomReadyChanged::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .se.common.EntityId entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_entity_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ready = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ready_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* N_RoomReadyChanged::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.N_RoomReadyChanged)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .se.common.EntityId entity_id = 1;
  if (this->_internal_has_entity_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::entity_id(this),
        _Internal::entity_id(this).GetCachedSize(), target, stream);
  }

  // bool ready = 2;
  if (this->_internal_ready() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_ready(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.N_RoomReadyChanged)
  return target;
}

size_t N_RoomReadyChanged::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.N_RoomReadyChanged)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .se.common.EntityId entity_id = 1;
  if (this->_internal_has_entity_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.entity_id_);
  }

  // bool ready = 2;
  if (this->_internal_ready() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData N_RoomReadyChanged::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    N_RoomReadyChanged::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*N_RoomReadyChanged::GetClassData() const { return &_class_data_; }


void N_RoomReadyChanged::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<N_RoomReadyChanged*>(&to_msg);
  auto& from = static_cast<const N_RoomReadyChanged&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.N_RoomReadyChanged)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_entity_id()) {
    _this->_internal_mutable_entity_id()->::se::common::EntityId::MergeFrom(
        from._internal_entity_id());
  }
  if (from._internal_ready() != 0) {
    _this->_internal_set_ready(from._internal_ready());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void N_RoomReadyChanged::CopyFrom(const N_RoomReadyChanged& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.N_RoomReadyChanged)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool N_RoomReadyChanged::IsInitialized() const {
  return true;
}

void N_RoomReadyChanged::InternalSwap(N_RoomReadyChanged* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(N_RoomReadyChanged, _impl_.ready_)
      + sizeof(N_RoomReadyChanged::_impl_.ready_)
      - PROTOBUF_FIELD_OFFSET(N_RoomReadyChanged, _impl_.entity_id_)>(
          reinterpret_cast<char*>(&_impl_.entity_id_),
          reinterpret_cast<char*>(&other->_impl_.entity_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata N_RoomReadyChanged::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[1]);
}

// ===================================================================

class N_GameStart::_Internal {
 public:
};

N_GameStart::N_GameStart(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:se.room.N_GameStart)
}
N_GameStart::N_GameStart(const N_GameStart& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  N_GameStart* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:se.room.N_GameStart)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData N_GameStart::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*N_GameStart::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata N_GameStart::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[2]);
}

// ===================================================================

class C_MoveInput::_Internal {
 public:
};

C_MoveInput::C_MoveInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.C_MoveInput)
}
C_MoveInput::C_MoveInput(const C_MoveInput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_MoveInput* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.move_x_){}
    , decltype(_impl_.move_y_){}
    , decltype(_impl_.yaw_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.move_x_, &from._impl_.move_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.yaw_) -
    reinterpret_cast<char*>(&_impl_.move_x_)) + sizeof(_impl_.yaw_));
  // @@protoc_insertion_point(copy_constructor:se.room.C_MoveInput)
}

inline void C_MoveInput::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.move_x_){0}
    , decltype(_impl_.move_y_){0}
    , decltype(_impl_.yaw_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C_MoveInput::~C_MoveInput() {
  // @@protoc_insertion_point(destructor:se.room.C_MoveInput)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_MoveInput::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C_MoveInput::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_MoveInput::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.C_MoveInput)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.move_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.yaw_) -
      reinterpret_cast<char*>(&_impl_.move_x_)) + sizeof(_impl_.yaw_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_MoveInput::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float move_x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.move_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float move_y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.move_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float yaw = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_MoveInput::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.C_MoveInput)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float move_x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_move_x = this->_internal_move_x();
  uint32_t raw_move_x;
  memcpy(&raw_move_x, &tmp_move_x, sizeof(tmp_move_x));
  if (raw_move_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_move_x(), target);
  }

  // float move_y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_move_y = this->_internal_move_y();
  uint32_t raw_move_y;
  memcpy(&raw_move_y, &tmp_move_y, sizeof(tmp_move_y));
  if (raw_move_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_move_y(), target);
  }

  // float yaw = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_yaw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.C_MoveInput)
  return target;
}

size_t C_MoveInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.C_MoveInput)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float move_x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_move_x = this->_internal_move_x();
  uint32_t raw_move_x;
  memcpy(&raw_move_x, &tmp_move_x, sizeof(tmp_move_x));
  if (raw_move_x != 0) {
    total_size += 1 + 4;
  }

  // float move_y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_move_y = this->_internal_move_y();
  uint32_t raw_move_y;
  memcpy(&raw_move_y, &tmp_move_y, sizeof(tmp_move_y));
  if (raw_move_y != 0) {
    total_size += 1 + 4;
  }

  // float yaw = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_MoveInput::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_MoveInput::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_MoveInput::GetClassData() const { return &_class_data_; }


void C_MoveInput::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_MoveInput*>(&to_msg);
  auto& from = static_cast<const C_MoveInput&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.C_MoveInput)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_move_x = from._internal_move_x();
  uint32_t raw_move_x;
  memcpy(&raw_move_x, &tmp_move_x, sizeof(tmp_move_x));
  if (raw_move_x != 0) {
    _this->_internal_set_move_x(from._internal_move_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_move_y = from._internal_move_y();
  uint32_t raw_move_y;
  memcpy(&raw_move_y, &tmp_move_y, sizeof(tmp_move_y));
  if (raw_move_y != 0) {
    _this->_internal_set_move_y(from._internal_move_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = from._internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    _this->_internal_set_yaw(from._internal_yaw());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_MoveInput::CopyFrom(const C_MoveInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.C_MoveInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_MoveInput::IsInitialized() const {
  return true;
}

void C_MoveInput::InternalSwap(C_MoveInput* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_MoveInput, _impl_.yaw_)
      + sizeof(C_MoveInput::_impl_.yaw_)
      - PROTOBUF_FIELD_OFFSET(C_MoveInput, _impl_.move_x_)>(
          reinterpret_cast<char*>(&_impl_.move_x_),
          reinterpret_cast<char*>(&other->_impl_.move_x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C_MoveInput::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[3]);
}

// ===================================================================

class C_AimInput::_Internal {
 public:
};

C_AimInput::C_AimInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.C_AimInput)
}
C_AimInput::C_AimInput(const C_AimInput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_AimInput* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pitch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.pitch_ = from._impl_.pitch_;
  // @@protoc_insertion_point(copy_constructor:se.room.C_AimInput)
}

inline void C_AimInput::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pitch_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C_AimInput::~C_AimInput() {
  // @@protoc_insertion_point(destructor:se.room.C_AimInput)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_AimInput::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C_AimInput::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_AimInput::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.C_AimInput)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pitch_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_AimInput::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float pitch = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_AimInput::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.C_AimInput)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float pitch = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_pitch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.C_AimInput)
  return target;
}

size_t C_AimInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.C_AimInput)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float pitch = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_AimInput::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_AimInput::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_AimInput::GetClassData() const { return &_class_data_; }


void C_AimInput::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_AimInput*>(&to_msg);
  auto& from = static_cast<const C_AimInput&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.C_AimInput)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = from._internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    _this->_internal_set_pitch(from._internal_pitch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_AimInput::CopyFrom(const C_AimInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.C_AimInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_AimInput::IsInitialized() const {
  return true;
}

void C_AimInput::InternalSwap(C_AimInput* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.pitch_, other->_impl_.pitch_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C_AimInput::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[4]);
}

// ===================================================================

class C_FireReq::_Internal {
 public:
};

C_FireReq::C_FireReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.C_FireReq)
}
C_FireReq::C_FireReq(const C_FireReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_FireReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.weapon_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.weapon_id_ = from._impl_.weapon_id_;
  // @@protoc_insertion_point(copy_constructor:se.room.C_FireReq)
}

inline void C_FireReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.weapon_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C_FireReq::~C_FireReq() {
  // @@protoc_insertion_point(destructor:se.room.C_FireReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_FireReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C_FireReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_FireReq::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.C_FireReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.weapon_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_FireReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 weapon_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.weapon_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_FireReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.C_FireReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 weapon_id = 1;
  if (this->_internal_weapon_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_weapon_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.C_FireReq)
  return target;
}

size_t C_FireReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.C_FireReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 weapon_id = 1;
  if (this->_internal_weapon_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_weapon_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_FireReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_FireReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_FireReq::GetClassData() const { return &_class_data_; }


void C_FireReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_FireReq*>(&to_msg);
  auto& from = static_cast<const C_FireReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.C_FireReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_weapon_id() != 0) {
    _this->_internal_set_weapon_id(from._internal_weapon_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_FireReq::CopyFrom(const C_FireReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.C_FireReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_FireReq::IsInitialized() const {
  return true;
}

void C_FireReq::InternalSwap(C_FireReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.weapon_id_, other->_impl_.weapon_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C_FireReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[5]);
}

// ===================================================================

class S_EntityState::_Internal {
 public:
};

void S_EntityState::clear_entities() {
  _impl_.entities_.Clear();
}
S_EntityState::S_EntityState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.S_EntityState)
}
S_EntityState::S_EntityState(const S_EntityState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_EntityState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entities_){from._impl_.entities_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:se.room.S_EntityState)
}

inline void S_EntityState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entities_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S_EntityState::~S_EntityState() {
  // @@protoc_insertion_point(destructor:se.room.S_EntityState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_EntityState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.entities_.~RepeatedPtrField();
}

void S_EntityState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_EntityState::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.S_EntityState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entities_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_EntityState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .se.room.EntityState entities = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_entities(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_EntityState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.S_EntityState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .se.room.EntityState entities = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_entities_size()); i < n; i++) {
    const auto& repfield = this->_internal_entities(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.S_EntityState)
  return target;
}

size_t S_EntityState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.S_EntityState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .se.room.EntityState entities = 1;
  total_size += 1UL * this->_internal_entities_size();
  for (const auto& msg : this->_impl_.entities_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_EntityState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_EntityState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_EntityState::GetClassData() const { return &_class_data_; }


void S_EntityState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_EntityState*>(&to_msg);
  auto& from = static_cast<const S_EntityState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.S_EntityState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.entities_.MergeFrom(from._impl_.entities_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_EntityState::CopyFrom(const S_EntityState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.S_EntityState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_EntityState::IsInitialized() const {
  return true;
}

void S_EntityState::InternalSwap(S_EntityState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entities_.InternalSwap(&other->_impl_.entities_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S_EntityState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[6]);
}

// ===================================================================

class N_EntitySpawn::_Internal {
 public:
  static const ::se::room::EntityState& entity(const N_EntitySpawn* msg);
};

const ::se::room::EntityState&
N_EntitySpawn::_Internal::entity(const N_EntitySpawn* msg) {
  return *msg->_impl_.entity_;
}
void N_EntitySpawn::clear_entity() {
  if (GetArenaForAllocation() == nullptr && _impl_.entity_ != nullptr) {
    delete _impl_.entity_;
  }
  _impl_.entity_ = nullptr;
}
N_EntitySpawn::N_EntitySpawn(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.N_EntitySpawn)
}
N_EntitySpawn::N_EntitySpawn(const N_EntitySpawn& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  N_EntitySpawn* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_entity()) {
    _this->_impl_.entity_ = new ::se::room::EntityState(*from._impl_.entity_);
  }
  // @@protoc_insertion_point(copy_constructor:se.room.N_EntitySpawn)
}

inline void N_EntitySpawn::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

N_EntitySpawn::~N_EntitySpawn() {
  // @@protoc_insertion_point(destructor:se.room.N_EntitySpawn)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void N_EntitySpawn::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.entity_;
}

void N_EntitySpawn::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void N_EntitySpawn::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.N_EntitySpawn)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.entity_ != nullptr) {
    delete _impl_.entity_;
  }
  _impl_.entity_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* N_EntitySpawn::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .se.room.EntityState entity = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_entity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* N_EntitySpawn::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.N_EntitySpawn)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .se.room.EntityState entity = 1;
  if (this->_internal_has_entity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::entity(this),
        _Internal::entity(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.N_EntitySpawn)
  return target;
}

size_t N_EntitySpawn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.N_EntitySpawn)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .se.room.EntityState entity = 1;
  if (this->_internal_has_entity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.entity_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData N_EntitySpawn::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    N_EntitySpawn::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*N_EntitySpawn::GetClassData() const { return &_class_data_; }


void N_EntitySpawn::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<N_EntitySpawn*>(&to_msg);
  auto& from = static_cast<const N_EntitySpawn&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.N_EntitySpawn)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_entity()) {
    _this->_internal_mutable_entity()->::se::room::EntityState::MergeFrom(
        from._internal_entity());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void N_EntitySpawn::CopyFrom(const N_EntitySpawn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.N_EntitySpawn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool N_EntitySpawn::IsInitialized() const {
  return true;
}

void N_EntitySpawn::InternalSwap(N_EntitySpawn* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.entity_, other->_impl_.entity_);
}

::PROTOBUF_NAMESPACE_ID::Metadata N_EntitySpawn::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[7]);
}

// ===================================================================

class N_EntityDespawn::_Internal {
 public:
  static const ::se::common::EntityId& entity_id(const N_EntityDespawn* msg);
};

const ::se::common::EntityId&
N_EntityDespawn::_Internal::entity_id(const N_EntityDespawn* msg) {
  return *msg->_impl_.entity_id_;
}
void N_EntityDespawn::clear_entity_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
}
N_EntityDespawn::N_EntityDespawn(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.N_EntityDespawn)
}
N_EntityDespawn::N_EntityDespawn(const N_EntityDespawn& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  N_EntityDespawn* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_entity_id()) {
    _this->_impl_.entity_id_ = new ::se::common::EntityId(*from._impl_.entity_id_);
  }
  // @@protoc_insertion_point(copy_constructor:se.room.N_EntityDespawn)
}

inline void N_EntityDespawn::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

N_EntityDespawn::~N_EntityDespawn() {
  // @@protoc_insertion_point(destructor:se.room.N_EntityDespawn)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void N_EntityDespawn::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.entity_id_;
}

void N_EntityDespawn::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void N_EntityDespawn::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.N_EntityDespawn)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* N_EntityDespawn::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .se.common.EntityId entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_entity_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* N_EntityDespawn::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.N_EntityDespawn)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .se.common.EntityId entity_id = 1;
  if (this->_internal_has_entity_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::entity_id(this),
        _Internal::entity_id(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.N_EntityDespawn)
  return target;
}

size_t N_EntityDespawn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.N_EntityDespawn)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .se.common.EntityId entity_id = 1;
  if (this->_internal_has_entity_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.entity_id_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData N_EntityDespawn::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    N_EntityDespawn::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*N_EntityDespawn::GetClassData() const { return &_class_data_; }


void N_EntityDespawn::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<N_EntityDespawn*>(&to_msg);
  auto& from = static_cast<const N_EntityDespawn&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.N_EntityDespawn)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_entity_id()) {
    _this->_internal_mutable_entity_id()->::se::common::EntityId::MergeFrom(
        from._internal_entity_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void N_EntityDespawn::CopyFrom(const N_EntityDespawn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.N_EntityDespawn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool N_EntityDespawn::IsInitialized() const {
  return true;
}

void N_EntityDespawn::InternalSwap(N_EntityDespawn* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.entity_id_, other->_impl_.entity_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata N_EntityDespawn::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[8]);
}

// ===================================================================

class N_HitEvent::_Internal {
 public:
  static const ::se::common::EntityId& attacker(const N_HitEvent* msg);
  static const ::se::common::EntityId& victim(const N_HitEvent* msg);
};

const ::se::common::EntityId&
N_HitEvent::_Internal::attacker(const N_HitEvent* msg) {
  return *msg->_impl_.attacker_;
}
const ::se::common::EntityId&
N_HitEvent::_Internal::victim(const N_HitEvent* msg) {
  return *msg->_impl_.victim_;
}
void N_HitEvent::clear_attacker() {
  if (GetArenaForAllocation() == nullptr && _impl_.attacker_ != nullptr) {
    delete _impl_.attacker_;
  }
  _impl_.attacker_ = nullptr;
}
void N_HitEvent::clear_victim() {
  if (GetArenaForAllocation() == nullptr && _impl_.victim_ != nullptr) {
    delete _impl_.victim_;
  }
  _impl_.victim_ = nullptr;
}
N_HitEvent::N_HitEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.N_HitEvent)
}
N_HitEvent::N_HitEvent(const N_HitEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  N_HitEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.attacker_){nullptr}
    , decltype(_impl_.victim_){nullptr}
    , decltype(_impl_.damage_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_attacker()) {
    _this->_impl_.attacker_ = new ::se::common::EntityId(*from._impl_.attacker_);
  }
  if (from._internal_has_victim()) {
    _this->_impl_.victim_ = new ::se::common::EntityId(*from._impl_.victim_);
  }
  _this->_impl_.damage_ = from._impl_.damage_;
  // @@protoc_insertion_point(copy_constructor:se.room.N_HitEvent)
}

inline void N_HitEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.attacker_){nullptr}
    , decltype(_impl_.victim_){nullptr}
    , decltype(_impl_.damage_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

N_HitEvent::~N_HitEvent() {
  // @@protoc_insertion_point(destructor:se.room.N_HitEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void N_HitEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.attacker_;
  if (this != internal_default_instance()) delete _impl_.victim_;
}

void N_HitEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void N_HitEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.N_HitEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.attacker_ != nullptr) {
    delete _impl_.attacker_;
  }
  _impl_.attacker_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.victim_ != nullptr) {
    delete _impl_.victim_;
  }
  _impl_.victim_ = nullptr;
  _impl_.damage_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* N_HitEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .se.common.EntityId attacker = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_attacker(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .se.common.EntityId victim = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_victim(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 damage = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.damage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* N_HitEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.N_HitEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .se.common.EntityId attacker = 1;
  if (this->_internal_has_attacker()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::attacker(this),
        _Internal::attacker(this).GetCachedSize(), target, stream);
  }

  // .se.common.EntityId victim = 2;
  if (this->_internal_has_victim()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::victim(this),
        _Internal::victim(this).GetCachedSize(), target, stream);
  }

  // uint32 damage = 3;
  if (this->_internal_damage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_damage(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.N_HitEvent)
  return target;
}

size_t N_HitEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.N_HitEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .se.common.EntityId attacker = 1;
  if (this->_internal_has_attacker()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.attacker_);
  }

  // .se.common.EntityId victim = 2;
  if (this->_internal_has_victim()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.victim_);
  }

  // uint32 damage = 3;
  if (this->_internal_damage() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_damage());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData N_HitEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    N_HitEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*N_HitEvent::GetClassData() const { return &_class_data_; }


void N_HitEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<N_HitEvent*>(&to_msg);
  auto& from = static_cast<const N_HitEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.N_HitEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_attacker()) {
    _this->_internal_mutable_attacker()->::se::common::EntityId::MergeFrom(
        from._internal_attacker());
  }
  if (from._internal_has_victim()) {
    _this->_internal_mutable_victim()->::se::common::EntityId::MergeFrom(
        from._internal_victim());
  }
  if (from._internal_damage() != 0) {
    _this->_internal_set_damage(from._internal_damage());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void N_HitEvent::CopyFrom(const N_HitEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.N_HitEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool N_HitEvent::IsInitialized() const {
  return true;
}

void N_HitEvent::InternalSwap(N_HitEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(N_HitEvent, _impl_.damage_)
      + sizeof(N_HitEvent::_impl_.damage_)
      - PROTOBUF_FIELD_OFFSET(N_HitEvent, _impl_.attacker_)>(
          reinterpret_cast<char*>(&_impl_.attacker_),
          reinterpret_cast<char*>(&other->_impl_.attacker_));
}

::PROTOBUF_NAMESPACE_ID::Metadata N_HitEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5fmessages_2eproto_getter, &descriptor_table_room_2froom_5fmessages_2eproto_once,
      file_level_metadata_room_2froom_5fmessages_2eproto[9]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace room
}  // namespace se
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::se::room::C_RoomReadyReq*
Arena::CreateMaybeMessage< ::se::room::C_RoomReadyReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::C_RoomReadyReq >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::N_RoomReadyChanged*
Arena::CreateMaybeMessage< ::se::room::N_RoomReadyChanged >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::N_RoomReadyChanged >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::N_GameStart*
Arena::CreateMaybeMessage< ::se::room::N_GameStart >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::N_GameStart >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::C_MoveInput*
Arena::CreateMaybeMessage< ::se::room::C_MoveInput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::C_MoveInput >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::C_AimInput*
Arena::CreateMaybeMessage< ::se::room::C_AimInput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::C_AimInput >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::C_FireReq*
Arena::CreateMaybeMessage< ::se::room::C_FireReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::C_FireReq >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::S_EntityState*
Arena::CreateMaybeMessage< ::se::room::S_EntityState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::S_EntityState >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::N_EntitySpawn*
Arena::CreateMaybeMessage< ::se::room::N_EntitySpawn >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::N_EntitySpawn >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::N_EntityDespawn*
Arena::CreateMaybeMessage< ::se::room::N_EntityDespawn >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::N_EntityDespawn >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::N_HitEvent*
Arena::CreateMaybeMessage< ::se::room::N_HitEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::N_HitEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
