// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room/room_types.proto

#include "room/room_types.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace se {
namespace room {
PROTOBUF_CONSTEXPR RoomPlayer::RoomPlayer(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nickname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.player_id_)*/nullptr
  , /*decltype(_impl_.entity_id_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RoomPlayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoomPlayerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoomPlayerDefaultTypeInternal() {}
  union {
    RoomPlayer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoomPlayerDefaultTypeInternal _RoomPlayer_default_instance_;
PROTOBUF_CONSTEXPR RoomSnapshot::RoomSnapshot(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.players_)*/{}
  , /*decltype(_impl_.room_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RoomSnapshotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoomSnapshotDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoomSnapshotDefaultTypeInternal() {}
  union {
    RoomSnapshot _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoomSnapshotDefaultTypeInternal _RoomSnapshot_default_instance_;
PROTOBUF_CONSTEXPR SpawnInfo::SpawnInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_id_)*/nullptr
  , /*decltype(_impl_.movement_)*/nullptr
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.template_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpawnInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpawnInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpawnInfoDefaultTypeInternal() {}
  union {
    SpawnInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpawnInfoDefaultTypeInternal _SpawnInfo_default_instance_;
}  // namespace room
}  // namespace se
static ::_pb::Metadata file_level_metadata_room_2froom_5ftypes_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_room_2froom_5ftypes_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_room_2froom_5ftypes_2eproto = nullptr;

const uint32_t TableStruct_room_2froom_5ftypes_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::RoomPlayer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::RoomPlayer, _impl_.player_id_),
  PROTOBUF_FIELD_OFFSET(::se::room::RoomPlayer, _impl_.entity_id_),
  PROTOBUF_FIELD_OFFSET(::se::room::RoomPlayer, _impl_.nickname_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::RoomSnapshot, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::RoomSnapshot, _impl_.room_id_),
  PROTOBUF_FIELD_OFFSET(::se::room::RoomSnapshot, _impl_.players_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::se::room::SpawnInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::se::room::SpawnInfo, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::se::room::SpawnInfo, _impl_.template_id_),
  PROTOBUF_FIELD_OFFSET(::se::room::SpawnInfo, _impl_.entity_id_),
  PROTOBUF_FIELD_OFFSET(::se::room::SpawnInfo, _impl_.movement_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::se::room::RoomPlayer)},
  { 9, -1, -1, sizeof(::se::room::RoomSnapshot)},
  { 17, -1, -1, sizeof(::se::room::SpawnInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::se::room::_RoomPlayer_default_instance_._instance,
  &::se::room::_RoomSnapshot_default_instance_._instance,
  &::se::room::_SpawnInfo_default_instance_._instance,
};

const char descriptor_table_protodef_room_2froom_5ftypes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025room/room_types.proto\022\007se.room\032\031common"
  "/common_types.proto\032\031common/common_enums"
  ".proto\"n\n\nRoomPlayer\022&\n\tplayer_id\030\001 \001(\0132"
  "\023.se.common.PlayerId\022&\n\tentity_id\030\002 \001(\0132"
  "\023.se.common.ObjectId\022\020\n\010nickname\030\003 \001(\t\"E"
  "\n\014RoomSnapshot\022\017\n\007room_id\030\001 \001(\r\022$\n\007playe"
  "rs\030\002 \003(\0132\023.se.room.RoomPlayer\"\231\001\n\tSpawnI"
  "nfo\022#\n\004type\030\001 \001(\0162\025.se.common.ObjectType"
  "\022\023\n\013template_id\030\002 \001(\r\022&\n\tentity_id\030\003 \001(\013"
  "2\023.se.common.ObjectId\022*\n\010movement\030\004 \001(\0132"
  "\030.se.common.MovementStateb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_room_2froom_5ftypes_2eproto_deps[2] = {
  &::descriptor_table_common_2fcommon_5fenums_2eproto,
  &::descriptor_table_common_2fcommon_5ftypes_2eproto,
};
static ::_pbi::once_flag descriptor_table_room_2froom_5ftypes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_room_2froom_5ftypes_2eproto = {
    false, false, 433, descriptor_table_protodef_room_2froom_5ftypes_2eproto,
    "room/room_types.proto",
    &descriptor_table_room_2froom_5ftypes_2eproto_once, descriptor_table_room_2froom_5ftypes_2eproto_deps, 2, 3,
    schemas, file_default_instances, TableStruct_room_2froom_5ftypes_2eproto::offsets,
    file_level_metadata_room_2froom_5ftypes_2eproto, file_level_enum_descriptors_room_2froom_5ftypes_2eproto,
    file_level_service_descriptors_room_2froom_5ftypes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_room_2froom_5ftypes_2eproto_getter() {
  return &descriptor_table_room_2froom_5ftypes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_room_2froom_5ftypes_2eproto(&descriptor_table_room_2froom_5ftypes_2eproto);
namespace se {
namespace room {

// ===================================================================

class RoomPlayer::_Internal {
 public:
  static const ::se::common::PlayerId& player_id(const RoomPlayer* msg);
  static const ::se::common::ObjectId& entity_id(const RoomPlayer* msg);
};

const ::se::common::PlayerId&
RoomPlayer::_Internal::player_id(const RoomPlayer* msg) {
  return *msg->_impl_.player_id_;
}
const ::se::common::ObjectId&
RoomPlayer::_Internal::entity_id(const RoomPlayer* msg) {
  return *msg->_impl_.entity_id_;
}
void RoomPlayer::clear_player_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.player_id_ != nullptr) {
    delete _impl_.player_id_;
  }
  _impl_.player_id_ = nullptr;
}
void RoomPlayer::clear_entity_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
}
RoomPlayer::RoomPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.RoomPlayer)
}
RoomPlayer::RoomPlayer(const RoomPlayer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RoomPlayer* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nickname_){}
    , decltype(_impl_.player_id_){nullptr}
    , decltype(_impl_.entity_id_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.nickname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nickname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nickname().empty()) {
    _this->_impl_.nickname_.Set(from._internal_nickname(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_player_id()) {
    _this->_impl_.player_id_ = new ::se::common::PlayerId(*from._impl_.player_id_);
  }
  if (from._internal_has_entity_id()) {
    _this->_impl_.entity_id_ = new ::se::common::ObjectId(*from._impl_.entity_id_);
  }
  // @@protoc_insertion_point(copy_constructor:se.room.RoomPlayer)
}

inline void RoomPlayer::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nickname_){}
    , decltype(_impl_.player_id_){nullptr}
    , decltype(_impl_.entity_id_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.nickname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nickname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RoomPlayer::~RoomPlayer() {
  // @@protoc_insertion_point(destructor:se.room.RoomPlayer)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RoomPlayer::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nickname_.Destroy();
  if (this != internal_default_instance()) delete _impl_.player_id_;
  if (this != internal_default_instance()) delete _impl_.entity_id_;
}

void RoomPlayer::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RoomPlayer::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.RoomPlayer)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nickname_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.player_id_ != nullptr) {
    delete _impl_.player_id_;
  }
  _impl_.player_id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RoomPlayer::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .se.common.PlayerId player_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_player_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .se.common.ObjectId entity_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_entity_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string nickname = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_nickname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "se.room.RoomPlayer.nickname"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RoomPlayer::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.RoomPlayer)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .se.common.PlayerId player_id = 1;
  if (this->_internal_has_player_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::player_id(this),
        _Internal::player_id(this).GetCachedSize(), target, stream);
  }

  // .se.common.ObjectId entity_id = 2;
  if (this->_internal_has_entity_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::entity_id(this),
        _Internal::entity_id(this).GetCachedSize(), target, stream);
  }

  // string nickname = 3;
  if (!this->_internal_nickname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_nickname().data(), static_cast<int>(this->_internal_nickname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "se.room.RoomPlayer.nickname");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_nickname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.RoomPlayer)
  return target;
}

size_t RoomPlayer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.RoomPlayer)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nickname = 3;
  if (!this->_internal_nickname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_nickname());
  }

  // .se.common.PlayerId player_id = 1;
  if (this->_internal_has_player_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.player_id_);
  }

  // .se.common.ObjectId entity_id = 2;
  if (this->_internal_has_entity_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.entity_id_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RoomPlayer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RoomPlayer::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RoomPlayer::GetClassData() const { return &_class_data_; }


void RoomPlayer::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RoomPlayer*>(&to_msg);
  auto& from = static_cast<const RoomPlayer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.RoomPlayer)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (from._internal_has_player_id()) {
    _this->_internal_mutable_player_id()->::se::common::PlayerId::MergeFrom(
        from._internal_player_id());
  }
  if (from._internal_has_entity_id()) {
    _this->_internal_mutable_entity_id()->::se::common::ObjectId::MergeFrom(
        from._internal_entity_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RoomPlayer::CopyFrom(const RoomPlayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.RoomPlayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomPlayer::IsInitialized() const {
  return true;
}

void RoomPlayer::InternalSwap(RoomPlayer* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nickname_, lhs_arena,
      &other->_impl_.nickname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RoomPlayer, _impl_.entity_id_)
      + sizeof(RoomPlayer::_impl_.entity_id_)
      - PROTOBUF_FIELD_OFFSET(RoomPlayer, _impl_.player_id_)>(
          reinterpret_cast<char*>(&_impl_.player_id_),
          reinterpret_cast<char*>(&other->_impl_.player_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RoomPlayer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5ftypes_2eproto_getter, &descriptor_table_room_2froom_5ftypes_2eproto_once,
      file_level_metadata_room_2froom_5ftypes_2eproto[0]);
}

// ===================================================================

class RoomSnapshot::_Internal {
 public:
};

RoomSnapshot::RoomSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.RoomSnapshot)
}
RoomSnapshot::RoomSnapshot(const RoomSnapshot& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RoomSnapshot* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.players_){from._impl_.players_}
    , decltype(_impl_.room_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.room_id_ = from._impl_.room_id_;
  // @@protoc_insertion_point(copy_constructor:se.room.RoomSnapshot)
}

inline void RoomSnapshot::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.players_){arena}
    , decltype(_impl_.room_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RoomSnapshot::~RoomSnapshot() {
  // @@protoc_insertion_point(destructor:se.room.RoomSnapshot)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RoomSnapshot::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.players_.~RepeatedPtrField();
}

void RoomSnapshot::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RoomSnapshot::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.RoomSnapshot)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.players_.Clear();
  _impl_.room_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RoomSnapshot::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 room_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.room_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .se.room.RoomPlayer players = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_players(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RoomSnapshot::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.RoomSnapshot)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 room_id = 1;
  if (this->_internal_room_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_room_id(), target);
  }

  // repeated .se.room.RoomPlayer players = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_players_size()); i < n; i++) {
    const auto& repfield = this->_internal_players(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.RoomSnapshot)
  return target;
}

size_t RoomSnapshot::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.RoomSnapshot)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .se.room.RoomPlayer players = 2;
  total_size += 1UL * this->_internal_players_size();
  for (const auto& msg : this->_impl_.players_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 room_id = 1;
  if (this->_internal_room_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_room_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RoomSnapshot::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RoomSnapshot::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RoomSnapshot::GetClassData() const { return &_class_data_; }


void RoomSnapshot::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RoomSnapshot*>(&to_msg);
  auto& from = static_cast<const RoomSnapshot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.RoomSnapshot)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.players_.MergeFrom(from._impl_.players_);
  if (from._internal_room_id() != 0) {
    _this->_internal_set_room_id(from._internal_room_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RoomSnapshot::CopyFrom(const RoomSnapshot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.RoomSnapshot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomSnapshot::IsInitialized() const {
  return true;
}

void RoomSnapshot::InternalSwap(RoomSnapshot* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.players_.InternalSwap(&other->_impl_.players_);
  swap(_impl_.room_id_, other->_impl_.room_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RoomSnapshot::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5ftypes_2eproto_getter, &descriptor_table_room_2froom_5ftypes_2eproto_once,
      file_level_metadata_room_2froom_5ftypes_2eproto[1]);
}

// ===================================================================

class SpawnInfo::_Internal {
 public:
  static const ::se::common::ObjectId& entity_id(const SpawnInfo* msg);
  static const ::se::common::MovementState& movement(const SpawnInfo* msg);
};

const ::se::common::ObjectId&
SpawnInfo::_Internal::entity_id(const SpawnInfo* msg) {
  return *msg->_impl_.entity_id_;
}
const ::se::common::MovementState&
SpawnInfo::_Internal::movement(const SpawnInfo* msg) {
  return *msg->_impl_.movement_;
}
void SpawnInfo::clear_entity_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
}
void SpawnInfo::clear_movement() {
  if (GetArenaForAllocation() == nullptr && _impl_.movement_ != nullptr) {
    delete _impl_.movement_;
  }
  _impl_.movement_ = nullptr;
}
SpawnInfo::SpawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:se.room.SpawnInfo)
}
SpawnInfo::SpawnInfo(const SpawnInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpawnInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){nullptr}
    , decltype(_impl_.movement_){nullptr}
    , decltype(_impl_.type_){}
    , decltype(_impl_.template_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_entity_id()) {
    _this->_impl_.entity_id_ = new ::se::common::ObjectId(*from._impl_.entity_id_);
  }
  if (from._internal_has_movement()) {
    _this->_impl_.movement_ = new ::se::common::MovementState(*from._impl_.movement_);
  }
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.template_id_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.template_id_));
  // @@protoc_insertion_point(copy_constructor:se.room.SpawnInfo)
}

inline void SpawnInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){nullptr}
    , decltype(_impl_.movement_){nullptr}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.template_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SpawnInfo::~SpawnInfo() {
  // @@protoc_insertion_point(destructor:se.room.SpawnInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpawnInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.entity_id_;
  if (this != internal_default_instance()) delete _impl_.movement_;
}

void SpawnInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpawnInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:se.room.SpawnInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.entity_id_ != nullptr) {
    delete _impl_.entity_id_;
  }
  _impl_.entity_id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.movement_ != nullptr) {
    delete _impl_.movement_;
  }
  _impl_.movement_ = nullptr;
  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.template_id_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.template_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpawnInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .se.common.ObjectType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::se::common::ObjectType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 template_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.template_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .se.common.ObjectId entity_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_entity_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .se.common.MovementState movement = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_movement(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpawnInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:se.room.SpawnInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .se.common.ObjectType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // uint32 template_id = 2;
  if (this->_internal_template_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_template_id(), target);
  }

  // .se.common.ObjectId entity_id = 3;
  if (this->_internal_has_entity_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::entity_id(this),
        _Internal::entity_id(this).GetCachedSize(), target, stream);
  }

  // .se.common.MovementState movement = 4;
  if (this->_internal_has_movement()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::movement(this),
        _Internal::movement(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:se.room.SpawnInfo)
  return target;
}

size_t SpawnInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:se.room.SpawnInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .se.common.ObjectId entity_id = 3;
  if (this->_internal_has_entity_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.entity_id_);
  }

  // .se.common.MovementState movement = 4;
  if (this->_internal_has_movement()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.movement_);
  }

  // .se.common.ObjectType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 template_id = 2;
  if (this->_internal_template_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_template_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpawnInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpawnInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpawnInfo::GetClassData() const { return &_class_data_; }


void SpawnInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpawnInfo*>(&to_msg);
  auto& from = static_cast<const SpawnInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:se.room.SpawnInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_entity_id()) {
    _this->_internal_mutable_entity_id()->::se::common::ObjectId::MergeFrom(
        from._internal_entity_id());
  }
  if (from._internal_has_movement()) {
    _this->_internal_mutable_movement()->::se::common::MovementState::MergeFrom(
        from._internal_movement());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_template_id() != 0) {
    _this->_internal_set_template_id(from._internal_template_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpawnInfo::CopyFrom(const SpawnInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:se.room.SpawnInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpawnInfo::IsInitialized() const {
  return true;
}

void SpawnInfo::InternalSwap(SpawnInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpawnInfo, _impl_.template_id_)
      + sizeof(SpawnInfo::_impl_.template_id_)
      - PROTOBUF_FIELD_OFFSET(SpawnInfo, _impl_.entity_id_)>(
          reinterpret_cast<char*>(&_impl_.entity_id_),
          reinterpret_cast<char*>(&other->_impl_.entity_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpawnInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_room_2froom_5ftypes_2eproto_getter, &descriptor_table_room_2froom_5ftypes_2eproto_once,
      file_level_metadata_room_2froom_5ftypes_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace room
}  // namespace se
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::se::room::RoomPlayer*
Arena::CreateMaybeMessage< ::se::room::RoomPlayer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::RoomPlayer >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::RoomSnapshot*
Arena::CreateMaybeMessage< ::se::room::RoomSnapshot >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::RoomSnapshot >(arena);
}
template<> PROTOBUF_NOINLINE ::se::room::SpawnInfo*
Arena::CreateMaybeMessage< ::se::room::SpawnInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::se::room::SpawnInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
