// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: options/packet_options.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_options_2fpacket_5foptions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_options_2fpacket_5foptions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_options_2fpacket_5foptions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_options_2fpacket_5foptions_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_options_2fpacket_5foptions_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace se {
namespace options {

enum PacketDir : int {
  DIR_NONE = 0,
  C2S = 1,
  S2C = 2,
  PacketDir_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PacketDir_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PacketDir_IsValid(int value);
constexpr PacketDir PacketDir_MIN = DIR_NONE;
constexpr PacketDir PacketDir_MAX = S2C;
constexpr int PacketDir_ARRAYSIZE = PacketDir_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PacketDir_descriptor();
template<typename T>
inline const std::string& PacketDir_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PacketDir>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PacketDir_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PacketDir_descriptor(), enum_t_value);
}
inline bool PacketDir_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PacketDir* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PacketDir>(
    PacketDir_descriptor(), name, value);
}
enum PacketRoute : int {
  ROUTE_NONE = 0,
  AUTH = 1,
  LOBBY = 2,
  ROOM = 3,
  PacketRoute_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PacketRoute_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PacketRoute_IsValid(int value);
constexpr PacketRoute PacketRoute_MIN = ROUTE_NONE;
constexpr PacketRoute PacketRoute_MAX = ROOM;
constexpr int PacketRoute_ARRAYSIZE = PacketRoute_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PacketRoute_descriptor();
template<typename T>
inline const std::string& PacketRoute_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PacketRoute>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PacketRoute_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PacketRoute_descriptor(), enum_t_value);
}
inline bool PacketRoute_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PacketRoute* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PacketRoute>(
    PacketRoute_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kPacketIdFieldNumber = 50001;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false >
  packet_id;
static const int kDirFieldNumber = 50002;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::se::options::PacketDir, ::se::options::PacketDir_IsValid>, 14, false >
  dir;
static const int kRouteFieldNumber = 50003;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::se::options::PacketRoute, ::se::options::PacketRoute_IsValid>, 14, false >
  route;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace options
}  // namespace se

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::se::options::PacketDir> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::se::options::PacketDir>() {
  return ::se::options::PacketDir_descriptor();
}
template <> struct is_proto_enum< ::se::options::PacketRoute> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::se::options::PacketRoute>() {
  return ::se::options::PacketRoute_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_options_2fpacket_5foptions_2eproto
