syntax = "proto3";

package se.game;

import "common/common_types.proto";
import "common/common_enums.proto";
import "game/game_enums.proto";

message PlayerMovement {
  float aim_yaw = 1;
  float pitch = 2;
  se.common.Vector2 velocity = 3;
  int32 movement_mode = 4;
}

message MonsterMovement {
  // TODO: Monster 고유 이동 상태 추가
}

message ProjectileMovement {
  se.common.Vector3 velocity = 1;
}

message WeaponStatSnapshot {
  int32 mag_capacity = 1;
  float fire_interval = 2;
  float reload_time = 3;
  
  int32 pellet_count = 4;
  float cone_angle = 5;
  
  float projectile_speed = 6;
  float explosion_radius = 7;
}

message WeaponSlotSnapshot {
  uint32 weapon_id = 1;
  WeaponStatSnapshot stat = 2;
}

message WeaponStatValue {
  WeaponStatType stat_type = 1;
  
  oneof value {
    int32 int_value = 2;
    float float_value = 3;
  }
}

message ItemStack {
  uint32 item_id = 1;
  uint32 amount = 2;
}

message SkillSlotSnapshot {
  uint32 slot_index = 1;
  uint32 skill_id = 2;
}

message StoreEntryInitData {
  uint32 store_item_id = 1;   // 상점 Entry ID (C_UseStoreReq.store_item_id와 동일한 값)
  int32 price = 2;            // 초기 표시 가격
}

message StoreEntryUpdateData {
  uint32 store_item_id = 1;   // 상점 Entry ID
  int32 price = 2;            // 업데이트된 가격
  bool is_available = 3;      // 구매 가능 여부
}

message TimeAccelEffect {
  uint32 fire_rate_bonus_percent = 1;    // 30 means +30%
  uint32 move_speed_bonus_percent = 2;   // 20 means +20%
}

message TimeAfterImageReq {
  se.common.Vector3 start_position = 1;   // 클라이언트가 스킬 사용을 시작한 위치
  se.common.Vector3 direction = 2;        // 잔상이 돌진할 방향
}

message TimeRewindReq {
  uint32 rewind_duration_ms = 1;                  // 클라이언트가 요청한 역행 시간
  se.common.Vector3 predicted_target_position = 2; // 클라이언트가 예상한 역행 후 위치
}

message TimeAfterImageEffect {
  se.common.Vector3 start_position = 1;
  se.common.Vector3 direction = 2;
  float move_speed = 3;
}

message TimeRewindEffect {
  uint32 rewind_duration_ms = 1;
  uint32 invulnerable_duration_ms = 2;
  int32 target_health = 3;
  se.common.Vector3 target_position = 4;
}
