// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test_messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_test_2ftest_5fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_test_2ftest_5fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "options/packet_options.pb.h"
#include "common/common_enums.pb.h"
#include "common/common_types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_test_2ftest_5fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_test_2ftest_5fmessages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_test_2ftest_5fmessages_2eproto;
namespace se {
namespace test {
class C_HealthReq;
struct C_HealthReqDefaultTypeInternal;
extern C_HealthReqDefaultTypeInternal _C_HealthReq_default_instance_;
class C_ItemReq;
struct C_ItemReqDefaultTypeInternal;
extern C_ItemReqDefaultTypeInternal _C_ItemReq_default_instance_;
class C_MaxHealthReq;
struct C_MaxHealthReqDefaultTypeInternal;
extern C_MaxHealthReqDefaultTypeInternal _C_MaxHealthReq_default_instance_;
class C_MoneyReq;
struct C_MoneyReqDefaultTypeInternal;
extern C_MoneyReqDefaultTypeInternal _C_MoneyReq_default_instance_;
class C_SpawnChestReq;
struct C_SpawnChestReqDefaultTypeInternal;
extern C_SpawnChestReqDefaultTypeInternal _C_SpawnChestReq_default_instance_;
class C_SpawnMonsterReq;
struct C_SpawnMonsterReqDefaultTypeInternal;
extern C_SpawnMonsterReqDefaultTypeInternal _C_SpawnMonsterReq_default_instance_;
class C_SpawnStoreReq;
struct C_SpawnStoreReqDefaultTypeInternal;
extern C_SpawnStoreReqDefaultTypeInternal _C_SpawnStoreReq_default_instance_;
class C_ZoneDamageOffReq;
struct C_ZoneDamageOffReqDefaultTypeInternal;
extern C_ZoneDamageOffReqDefaultTypeInternal _C_ZoneDamageOffReq_default_instance_;
class C_ZoneDamageOnReq;
struct C_ZoneDamageOnReqDefaultTypeInternal;
extern C_ZoneDamageOnReqDefaultTypeInternal _C_ZoneDamageOnReq_default_instance_;
class C_ZoneResetReq;
struct C_ZoneResetReqDefaultTypeInternal;
extern C_ZoneResetReqDefaultTypeInternal _C_ZoneResetReq_default_instance_;
class C_ZoneStartReq;
struct C_ZoneStartReqDefaultTypeInternal;
extern C_ZoneStartReqDefaultTypeInternal _C_ZoneStartReq_default_instance_;
class C_ZoneStopReq;
struct C_ZoneStopReqDefaultTypeInternal;
extern C_ZoneStopReqDefaultTypeInternal _C_ZoneStopReq_default_instance_;
class N_ZoneStart;
struct N_ZoneStartDefaultTypeInternal;
extern N_ZoneStartDefaultTypeInternal _N_ZoneStart_default_instance_;
class N_ZoneStop;
struct N_ZoneStopDefaultTypeInternal;
extern N_ZoneStopDefaultTypeInternal _N_ZoneStop_default_instance_;
}  // namespace test
}  // namespace se
PROTOBUF_NAMESPACE_OPEN
template<> ::se::test::C_HealthReq* Arena::CreateMaybeMessage<::se::test::C_HealthReq>(Arena*);
template<> ::se::test::C_ItemReq* Arena::CreateMaybeMessage<::se::test::C_ItemReq>(Arena*);
template<> ::se::test::C_MaxHealthReq* Arena::CreateMaybeMessage<::se::test::C_MaxHealthReq>(Arena*);
template<> ::se::test::C_MoneyReq* Arena::CreateMaybeMessage<::se::test::C_MoneyReq>(Arena*);
template<> ::se::test::C_SpawnChestReq* Arena::CreateMaybeMessage<::se::test::C_SpawnChestReq>(Arena*);
template<> ::se::test::C_SpawnMonsterReq* Arena::CreateMaybeMessage<::se::test::C_SpawnMonsterReq>(Arena*);
template<> ::se::test::C_SpawnStoreReq* Arena::CreateMaybeMessage<::se::test::C_SpawnStoreReq>(Arena*);
template<> ::se::test::C_ZoneDamageOffReq* Arena::CreateMaybeMessage<::se::test::C_ZoneDamageOffReq>(Arena*);
template<> ::se::test::C_ZoneDamageOnReq* Arena::CreateMaybeMessage<::se::test::C_ZoneDamageOnReq>(Arena*);
template<> ::se::test::C_ZoneResetReq* Arena::CreateMaybeMessage<::se::test::C_ZoneResetReq>(Arena*);
template<> ::se::test::C_ZoneStartReq* Arena::CreateMaybeMessage<::se::test::C_ZoneStartReq>(Arena*);
template<> ::se::test::C_ZoneStopReq* Arena::CreateMaybeMessage<::se::test::C_ZoneStopReq>(Arena*);
template<> ::se::test::N_ZoneStart* Arena::CreateMaybeMessage<::se::test::N_ZoneStart>(Arena*);
template<> ::se::test::N_ZoneStop* Arena::CreateMaybeMessage<::se::test::N_ZoneStop>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace se {
namespace test {

// ===================================================================

class C_SpawnMonsterReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_SpawnMonsterReq) */ {
 public:
  inline C_SpawnMonsterReq() : C_SpawnMonsterReq(nullptr) {}
  ~C_SpawnMonsterReq() override;
  explicit PROTOBUF_CONSTEXPR C_SpawnMonsterReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_SpawnMonsterReq(const C_SpawnMonsterReq& from);
  C_SpawnMonsterReq(C_SpawnMonsterReq&& from) noexcept
    : C_SpawnMonsterReq() {
    *this = ::std::move(from);
  }

  inline C_SpawnMonsterReq& operator=(const C_SpawnMonsterReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_SpawnMonsterReq& operator=(C_SpawnMonsterReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_SpawnMonsterReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_SpawnMonsterReq* internal_default_instance() {
    return reinterpret_cast<const C_SpawnMonsterReq*>(
               &_C_SpawnMonsterReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_SpawnMonsterReq& a, C_SpawnMonsterReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_SpawnMonsterReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_SpawnMonsterReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_SpawnMonsterReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_SpawnMonsterReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_SpawnMonsterReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_SpawnMonsterReq& from) {
    C_SpawnMonsterReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_SpawnMonsterReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_SpawnMonsterReq";
  }
  protected:
  explicit C_SpawnMonsterReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpawnPositionFieldNumber = 2,
    kEnemyTypeFieldNumber = 1,
  };
  // .se.common.Vector3 spawn_position = 2;
  bool has_spawn_position() const;
  private:
  bool _internal_has_spawn_position() const;
  public:
  void clear_spawn_position();
  const ::se::common::Vector3& spawn_position() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_spawn_position();
  ::se::common::Vector3* mutable_spawn_position();
  void set_allocated_spawn_position(::se::common::Vector3* spawn_position);
  private:
  const ::se::common::Vector3& _internal_spawn_position() const;
  ::se::common::Vector3* _internal_mutable_spawn_position();
  public:
  void unsafe_arena_set_allocated_spawn_position(
      ::se::common::Vector3* spawn_position);
  ::se::common::Vector3* unsafe_arena_release_spawn_position();

  // uint32 enemy_type = 1;
  void clear_enemy_type();
  uint32_t enemy_type() const;
  void set_enemy_type(uint32_t value);
  private:
  uint32_t _internal_enemy_type() const;
  void _internal_set_enemy_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.test.C_SpawnMonsterReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::Vector3* spawn_position_;
    uint32_t enemy_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_SpawnChestReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_SpawnChestReq) */ {
 public:
  inline C_SpawnChestReq() : C_SpawnChestReq(nullptr) {}
  ~C_SpawnChestReq() override;
  explicit PROTOBUF_CONSTEXPR C_SpawnChestReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_SpawnChestReq(const C_SpawnChestReq& from);
  C_SpawnChestReq(C_SpawnChestReq&& from) noexcept
    : C_SpawnChestReq() {
    *this = ::std::move(from);
  }

  inline C_SpawnChestReq& operator=(const C_SpawnChestReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_SpawnChestReq& operator=(C_SpawnChestReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_SpawnChestReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_SpawnChestReq* internal_default_instance() {
    return reinterpret_cast<const C_SpawnChestReq*>(
               &_C_SpawnChestReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(C_SpawnChestReq& a, C_SpawnChestReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_SpawnChestReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_SpawnChestReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_SpawnChestReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_SpawnChestReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_SpawnChestReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_SpawnChestReq& from) {
    C_SpawnChestReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_SpawnChestReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_SpawnChestReq";
  }
  protected:
  explicit C_SpawnChestReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpawnPositionFieldNumber = 2,
  };
  // .se.common.Vector3 spawn_position = 2;
  bool has_spawn_position() const;
  private:
  bool _internal_has_spawn_position() const;
  public:
  void clear_spawn_position();
  const ::se::common::Vector3& spawn_position() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_spawn_position();
  ::se::common::Vector3* mutable_spawn_position();
  void set_allocated_spawn_position(::se::common::Vector3* spawn_position);
  private:
  const ::se::common::Vector3& _internal_spawn_position() const;
  ::se::common::Vector3* _internal_mutable_spawn_position();
  public:
  void unsafe_arena_set_allocated_spawn_position(
      ::se::common::Vector3* spawn_position);
  ::se::common::Vector3* unsafe_arena_release_spawn_position();

  // @@protoc_insertion_point(class_scope:se.test.C_SpawnChestReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::Vector3* spawn_position_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_SpawnStoreReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_SpawnStoreReq) */ {
 public:
  inline C_SpawnStoreReq() : C_SpawnStoreReq(nullptr) {}
  ~C_SpawnStoreReq() override;
  explicit PROTOBUF_CONSTEXPR C_SpawnStoreReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_SpawnStoreReq(const C_SpawnStoreReq& from);
  C_SpawnStoreReq(C_SpawnStoreReq&& from) noexcept
    : C_SpawnStoreReq() {
    *this = ::std::move(from);
  }

  inline C_SpawnStoreReq& operator=(const C_SpawnStoreReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_SpawnStoreReq& operator=(C_SpawnStoreReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_SpawnStoreReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_SpawnStoreReq* internal_default_instance() {
    return reinterpret_cast<const C_SpawnStoreReq*>(
               &_C_SpawnStoreReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C_SpawnStoreReq& a, C_SpawnStoreReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_SpawnStoreReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_SpawnStoreReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_SpawnStoreReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_SpawnStoreReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_SpawnStoreReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_SpawnStoreReq& from) {
    C_SpawnStoreReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_SpawnStoreReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_SpawnStoreReq";
  }
  protected:
  explicit C_SpawnStoreReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpawnPositionFieldNumber = 2,
  };
  // .se.common.Vector3 spawn_position = 2;
  bool has_spawn_position() const;
  private:
  bool _internal_has_spawn_position() const;
  public:
  void clear_spawn_position();
  const ::se::common::Vector3& spawn_position() const;
  PROTOBUF_NODISCARD ::se::common::Vector3* release_spawn_position();
  ::se::common::Vector3* mutable_spawn_position();
  void set_allocated_spawn_position(::se::common::Vector3* spawn_position);
  private:
  const ::se::common::Vector3& _internal_spawn_position() const;
  ::se::common::Vector3* _internal_mutable_spawn_position();
  public:
  void unsafe_arena_set_allocated_spawn_position(
      ::se::common::Vector3* spawn_position);
  ::se::common::Vector3* unsafe_arena_release_spawn_position();

  // @@protoc_insertion_point(class_scope:se.test.C_SpawnStoreReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::se::common::Vector3* spawn_position_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_ItemReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_ItemReq) */ {
 public:
  inline C_ItemReq() : C_ItemReq(nullptr) {}
  ~C_ItemReq() override;
  explicit PROTOBUF_CONSTEXPR C_ItemReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ItemReq(const C_ItemReq& from);
  C_ItemReq(C_ItemReq&& from) noexcept
    : C_ItemReq() {
    *this = ::std::move(from);
  }

  inline C_ItemReq& operator=(const C_ItemReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ItemReq& operator=(C_ItemReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ItemReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ItemReq* internal_default_instance() {
    return reinterpret_cast<const C_ItemReq*>(
               &_C_ItemReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(C_ItemReq& a, C_ItemReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ItemReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ItemReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ItemReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ItemReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_ItemReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_ItemReq& from) {
    C_ItemReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_ItemReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_ItemReq";
  }
  protected:
  explicit C_ItemReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemIdFieldNumber = 1,
    kQuantityFieldNumber = 2,
  };
  // uint32 item_id = 1;
  void clear_item_id();
  uint32_t item_id() const;
  void set_item_id(uint32_t value);
  private:
  uint32_t _internal_item_id() const;
  void _internal_set_item_id(uint32_t value);
  public:

  // int32 quantity = 2;
  void clear_quantity();
  int32_t quantity() const;
  void set_quantity(int32_t value);
  private:
  int32_t _internal_quantity() const;
  void _internal_set_quantity(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.test.C_ItemReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t item_id_;
    int32_t quantity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_MoneyReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_MoneyReq) */ {
 public:
  inline C_MoneyReq() : C_MoneyReq(nullptr) {}
  ~C_MoneyReq() override;
  explicit PROTOBUF_CONSTEXPR C_MoneyReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_MoneyReq(const C_MoneyReq& from);
  C_MoneyReq(C_MoneyReq&& from) noexcept
    : C_MoneyReq() {
    *this = ::std::move(from);
  }

  inline C_MoneyReq& operator=(const C_MoneyReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_MoneyReq& operator=(C_MoneyReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_MoneyReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_MoneyReq* internal_default_instance() {
    return reinterpret_cast<const C_MoneyReq*>(
               &_C_MoneyReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C_MoneyReq& a, C_MoneyReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_MoneyReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_MoneyReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_MoneyReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_MoneyReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_MoneyReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_MoneyReq& from) {
    C_MoneyReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_MoneyReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_MoneyReq";
  }
  protected:
  explicit C_MoneyReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAmountFieldNumber = 1,
  };
  // int32 amount = 1;
  void clear_amount();
  int32_t amount() const;
  void set_amount(int32_t value);
  private:
  int32_t _internal_amount() const;
  void _internal_set_amount(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.test.C_MoneyReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t amount_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_HealthReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_HealthReq) */ {
 public:
  inline C_HealthReq() : C_HealthReq(nullptr) {}
  ~C_HealthReq() override;
  explicit PROTOBUF_CONSTEXPR C_HealthReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_HealthReq(const C_HealthReq& from);
  C_HealthReq(C_HealthReq&& from) noexcept
    : C_HealthReq() {
    *this = ::std::move(from);
  }

  inline C_HealthReq& operator=(const C_HealthReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_HealthReq& operator=(C_HealthReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_HealthReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_HealthReq* internal_default_instance() {
    return reinterpret_cast<const C_HealthReq*>(
               &_C_HealthReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(C_HealthReq& a, C_HealthReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_HealthReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_HealthReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_HealthReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_HealthReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_HealthReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_HealthReq& from) {
    C_HealthReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_HealthReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_HealthReq";
  }
  protected:
  explicit C_HealthReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHealthFieldNumber = 1,
  };
  // int32 health = 1;
  void clear_health();
  int32_t health() const;
  void set_health(int32_t value);
  private:
  int32_t _internal_health() const;
  void _internal_set_health(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.test.C_HealthReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t health_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_MaxHealthReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:se.test.C_MaxHealthReq) */ {
 public:
  inline C_MaxHealthReq() : C_MaxHealthReq(nullptr) {}
  ~C_MaxHealthReq() override;
  explicit PROTOBUF_CONSTEXPR C_MaxHealthReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_MaxHealthReq(const C_MaxHealthReq& from);
  C_MaxHealthReq(C_MaxHealthReq&& from) noexcept
    : C_MaxHealthReq() {
    *this = ::std::move(from);
  }

  inline C_MaxHealthReq& operator=(const C_MaxHealthReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_MaxHealthReq& operator=(C_MaxHealthReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_MaxHealthReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_MaxHealthReq* internal_default_instance() {
    return reinterpret_cast<const C_MaxHealthReq*>(
               &_C_MaxHealthReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(C_MaxHealthReq& a, C_MaxHealthReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_MaxHealthReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_MaxHealthReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_MaxHealthReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_MaxHealthReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_MaxHealthReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_MaxHealthReq& from) {
    C_MaxHealthReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_MaxHealthReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_MaxHealthReq";
  }
  protected:
  explicit C_MaxHealthReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxHealthFieldNumber = 1,
  };
  // int32 max_health = 1;
  void clear_max_health();
  int32_t max_health() const;
  void set_max_health(int32_t value);
  private:
  int32_t _internal_max_health() const;
  void _internal_set_max_health(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:se.test.C_MaxHealthReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t max_health_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_ZoneStopReq final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.C_ZoneStopReq) */ {
 public:
  inline C_ZoneStopReq() : C_ZoneStopReq(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C_ZoneStopReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ZoneStopReq(const C_ZoneStopReq& from);
  C_ZoneStopReq(C_ZoneStopReq&& from) noexcept
    : C_ZoneStopReq() {
    *this = ::std::move(from);
  }

  inline C_ZoneStopReq& operator=(const C_ZoneStopReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ZoneStopReq& operator=(C_ZoneStopReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ZoneStopReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ZoneStopReq* internal_default_instance() {
    return reinterpret_cast<const C_ZoneStopReq*>(
               &_C_ZoneStopReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(C_ZoneStopReq& a, C_ZoneStopReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ZoneStopReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ZoneStopReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ZoneStopReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ZoneStopReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C_ZoneStopReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C_ZoneStopReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_ZoneStopReq";
  }
  protected:
  explicit C_ZoneStopReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.C_ZoneStopReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_ZoneStartReq final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.C_ZoneStartReq) */ {
 public:
  inline C_ZoneStartReq() : C_ZoneStartReq(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C_ZoneStartReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ZoneStartReq(const C_ZoneStartReq& from);
  C_ZoneStartReq(C_ZoneStartReq&& from) noexcept
    : C_ZoneStartReq() {
    *this = ::std::move(from);
  }

  inline C_ZoneStartReq& operator=(const C_ZoneStartReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ZoneStartReq& operator=(C_ZoneStartReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ZoneStartReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ZoneStartReq* internal_default_instance() {
    return reinterpret_cast<const C_ZoneStartReq*>(
               &_C_ZoneStartReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(C_ZoneStartReq& a, C_ZoneStartReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ZoneStartReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ZoneStartReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ZoneStartReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ZoneStartReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C_ZoneStartReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C_ZoneStartReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_ZoneStartReq";
  }
  protected:
  explicit C_ZoneStartReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.C_ZoneStartReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_ZoneResetReq final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.C_ZoneResetReq) */ {
 public:
  inline C_ZoneResetReq() : C_ZoneResetReq(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C_ZoneResetReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ZoneResetReq(const C_ZoneResetReq& from);
  C_ZoneResetReq(C_ZoneResetReq&& from) noexcept
    : C_ZoneResetReq() {
    *this = ::std::move(from);
  }

  inline C_ZoneResetReq& operator=(const C_ZoneResetReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ZoneResetReq& operator=(C_ZoneResetReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ZoneResetReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ZoneResetReq* internal_default_instance() {
    return reinterpret_cast<const C_ZoneResetReq*>(
               &_C_ZoneResetReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(C_ZoneResetReq& a, C_ZoneResetReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ZoneResetReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ZoneResetReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ZoneResetReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ZoneResetReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C_ZoneResetReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C_ZoneResetReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_ZoneResetReq";
  }
  protected:
  explicit C_ZoneResetReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.C_ZoneResetReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_ZoneDamageOffReq final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.C_ZoneDamageOffReq) */ {
 public:
  inline C_ZoneDamageOffReq() : C_ZoneDamageOffReq(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C_ZoneDamageOffReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ZoneDamageOffReq(const C_ZoneDamageOffReq& from);
  C_ZoneDamageOffReq(C_ZoneDamageOffReq&& from) noexcept
    : C_ZoneDamageOffReq() {
    *this = ::std::move(from);
  }

  inline C_ZoneDamageOffReq& operator=(const C_ZoneDamageOffReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ZoneDamageOffReq& operator=(C_ZoneDamageOffReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ZoneDamageOffReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ZoneDamageOffReq* internal_default_instance() {
    return reinterpret_cast<const C_ZoneDamageOffReq*>(
               &_C_ZoneDamageOffReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(C_ZoneDamageOffReq& a, C_ZoneDamageOffReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ZoneDamageOffReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ZoneDamageOffReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ZoneDamageOffReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ZoneDamageOffReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C_ZoneDamageOffReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C_ZoneDamageOffReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_ZoneDamageOffReq";
  }
  protected:
  explicit C_ZoneDamageOffReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.C_ZoneDamageOffReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class C_ZoneDamageOnReq final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.C_ZoneDamageOnReq) */ {
 public:
  inline C_ZoneDamageOnReq() : C_ZoneDamageOnReq(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C_ZoneDamageOnReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ZoneDamageOnReq(const C_ZoneDamageOnReq& from);
  C_ZoneDamageOnReq(C_ZoneDamageOnReq&& from) noexcept
    : C_ZoneDamageOnReq() {
    *this = ::std::move(from);
  }

  inline C_ZoneDamageOnReq& operator=(const C_ZoneDamageOnReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ZoneDamageOnReq& operator=(C_ZoneDamageOnReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ZoneDamageOnReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ZoneDamageOnReq* internal_default_instance() {
    return reinterpret_cast<const C_ZoneDamageOnReq*>(
               &_C_ZoneDamageOnReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  friend void swap(C_ZoneDamageOnReq& a, C_ZoneDamageOnReq& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ZoneDamageOnReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ZoneDamageOnReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_ZoneDamageOnReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_ZoneDamageOnReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C_ZoneDamageOnReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C_ZoneDamageOnReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.C_ZoneDamageOnReq";
  }
  protected:
  explicit C_ZoneDamageOnReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.C_ZoneDamageOnReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class N_ZoneStop final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.N_ZoneStop) */ {
 public:
  inline N_ZoneStop() : N_ZoneStop(nullptr) {}
  explicit PROTOBUF_CONSTEXPR N_ZoneStop(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  N_ZoneStop(const N_ZoneStop& from);
  N_ZoneStop(N_ZoneStop&& from) noexcept
    : N_ZoneStop() {
    *this = ::std::move(from);
  }

  inline N_ZoneStop& operator=(const N_ZoneStop& from) {
    CopyFrom(from);
    return *this;
  }
  inline N_ZoneStop& operator=(N_ZoneStop&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const N_ZoneStop& default_instance() {
    return *internal_default_instance();
  }
  static inline const N_ZoneStop* internal_default_instance() {
    return reinterpret_cast<const N_ZoneStop*>(
               &_N_ZoneStop_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  friend void swap(N_ZoneStop& a, N_ZoneStop& b) {
    a.Swap(&b);
  }
  inline void Swap(N_ZoneStop* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(N_ZoneStop* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  N_ZoneStop* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<N_ZoneStop>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const N_ZoneStop& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const N_ZoneStop& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.N_ZoneStop";
  }
  protected:
  explicit N_ZoneStop(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.N_ZoneStop)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class N_ZoneStart final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:se.test.N_ZoneStart) */ {
 public:
  inline N_ZoneStart() : N_ZoneStart(nullptr) {}
  explicit PROTOBUF_CONSTEXPR N_ZoneStart(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  N_ZoneStart(const N_ZoneStart& from);
  N_ZoneStart(N_ZoneStart&& from) noexcept
    : N_ZoneStart() {
    *this = ::std::move(from);
  }

  inline N_ZoneStart& operator=(const N_ZoneStart& from) {
    CopyFrom(from);
    return *this;
  }
  inline N_ZoneStart& operator=(N_ZoneStart&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const N_ZoneStart& default_instance() {
    return *internal_default_instance();
  }
  static inline const N_ZoneStart* internal_default_instance() {
    return reinterpret_cast<const N_ZoneStart*>(
               &_N_ZoneStart_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  friend void swap(N_ZoneStart& a, N_ZoneStart& b) {
    a.Swap(&b);
  }
  inline void Swap(N_ZoneStart* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(N_ZoneStart* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  N_ZoneStart* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<N_ZoneStart>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const N_ZoneStart& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const N_ZoneStart& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "se.test.N_ZoneStart";
  }
  protected:
  explicit N_ZoneStart(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:se.test.N_ZoneStart)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_test_2ftest_5fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_SpawnMonsterReq

// .se.common.Vector3 spawn_position = 2;
inline bool C_SpawnMonsterReq::_internal_has_spawn_position() const {
  return this != internal_default_instance() && _impl_.spawn_position_ != nullptr;
}
inline bool C_SpawnMonsterReq::has_spawn_position() const {
  return _internal_has_spawn_position();
}
inline const ::se::common::Vector3& C_SpawnMonsterReq::_internal_spawn_position() const {
  const ::se::common::Vector3* p = _impl_.spawn_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& C_SpawnMonsterReq::spawn_position() const {
  // @@protoc_insertion_point(field_get:se.test.C_SpawnMonsterReq.spawn_position)
  return _internal_spawn_position();
}
inline void C_SpawnMonsterReq::unsafe_arena_set_allocated_spawn_position(
    ::se::common::Vector3* spawn_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.spawn_position_);
  }
  _impl_.spawn_position_ = spawn_position;
  if (spawn_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.test.C_SpawnMonsterReq.spawn_position)
}
inline ::se::common::Vector3* C_SpawnMonsterReq::release_spawn_position() {
  
  ::se::common::Vector3* temp = _impl_.spawn_position_;
  _impl_.spawn_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* C_SpawnMonsterReq::unsafe_arena_release_spawn_position() {
  // @@protoc_insertion_point(field_release:se.test.C_SpawnMonsterReq.spawn_position)
  
  ::se::common::Vector3* temp = _impl_.spawn_position_;
  _impl_.spawn_position_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* C_SpawnMonsterReq::_internal_mutable_spawn_position() {
  
  if (_impl_.spawn_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.spawn_position_ = p;
  }
  return _impl_.spawn_position_;
}
inline ::se::common::Vector3* C_SpawnMonsterReq::mutable_spawn_position() {
  ::se::common::Vector3* _msg = _internal_mutable_spawn_position();
  // @@protoc_insertion_point(field_mutable:se.test.C_SpawnMonsterReq.spawn_position)
  return _msg;
}
inline void C_SpawnMonsterReq::set_allocated_spawn_position(::se::common::Vector3* spawn_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.spawn_position_);
  }
  if (spawn_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(spawn_position));
    if (message_arena != submessage_arena) {
      spawn_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, spawn_position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.spawn_position_ = spawn_position;
  // @@protoc_insertion_point(field_set_allocated:se.test.C_SpawnMonsterReq.spawn_position)
}

// uint32 enemy_type = 1;
inline void C_SpawnMonsterReq::clear_enemy_type() {
  _impl_.enemy_type_ = 0u;
}
inline uint32_t C_SpawnMonsterReq::_internal_enemy_type() const {
  return _impl_.enemy_type_;
}
inline uint32_t C_SpawnMonsterReq::enemy_type() const {
  // @@protoc_insertion_point(field_get:se.test.C_SpawnMonsterReq.enemy_type)
  return _internal_enemy_type();
}
inline void C_SpawnMonsterReq::_internal_set_enemy_type(uint32_t value) {
  
  _impl_.enemy_type_ = value;
}
inline void C_SpawnMonsterReq::set_enemy_type(uint32_t value) {
  _internal_set_enemy_type(value);
  // @@protoc_insertion_point(field_set:se.test.C_SpawnMonsterReq.enemy_type)
}

// -------------------------------------------------------------------

// C_SpawnChestReq

// .se.common.Vector3 spawn_position = 2;
inline bool C_SpawnChestReq::_internal_has_spawn_position() const {
  return this != internal_default_instance() && _impl_.spawn_position_ != nullptr;
}
inline bool C_SpawnChestReq::has_spawn_position() const {
  return _internal_has_spawn_position();
}
inline const ::se::common::Vector3& C_SpawnChestReq::_internal_spawn_position() const {
  const ::se::common::Vector3* p = _impl_.spawn_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& C_SpawnChestReq::spawn_position() const {
  // @@protoc_insertion_point(field_get:se.test.C_SpawnChestReq.spawn_position)
  return _internal_spawn_position();
}
inline void C_SpawnChestReq::unsafe_arena_set_allocated_spawn_position(
    ::se::common::Vector3* spawn_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.spawn_position_);
  }
  _impl_.spawn_position_ = spawn_position;
  if (spawn_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.test.C_SpawnChestReq.spawn_position)
}
inline ::se::common::Vector3* C_SpawnChestReq::release_spawn_position() {
  
  ::se::common::Vector3* temp = _impl_.spawn_position_;
  _impl_.spawn_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* C_SpawnChestReq::unsafe_arena_release_spawn_position() {
  // @@protoc_insertion_point(field_release:se.test.C_SpawnChestReq.spawn_position)
  
  ::se::common::Vector3* temp = _impl_.spawn_position_;
  _impl_.spawn_position_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* C_SpawnChestReq::_internal_mutable_spawn_position() {
  
  if (_impl_.spawn_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.spawn_position_ = p;
  }
  return _impl_.spawn_position_;
}
inline ::se::common::Vector3* C_SpawnChestReq::mutable_spawn_position() {
  ::se::common::Vector3* _msg = _internal_mutable_spawn_position();
  // @@protoc_insertion_point(field_mutable:se.test.C_SpawnChestReq.spawn_position)
  return _msg;
}
inline void C_SpawnChestReq::set_allocated_spawn_position(::se::common::Vector3* spawn_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.spawn_position_);
  }
  if (spawn_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(spawn_position));
    if (message_arena != submessage_arena) {
      spawn_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, spawn_position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.spawn_position_ = spawn_position;
  // @@protoc_insertion_point(field_set_allocated:se.test.C_SpawnChestReq.spawn_position)
}

// -------------------------------------------------------------------

// C_SpawnStoreReq

// .se.common.Vector3 spawn_position = 2;
inline bool C_SpawnStoreReq::_internal_has_spawn_position() const {
  return this != internal_default_instance() && _impl_.spawn_position_ != nullptr;
}
inline bool C_SpawnStoreReq::has_spawn_position() const {
  return _internal_has_spawn_position();
}
inline const ::se::common::Vector3& C_SpawnStoreReq::_internal_spawn_position() const {
  const ::se::common::Vector3* p = _impl_.spawn_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::se::common::Vector3&>(
      ::se::common::_Vector3_default_instance_);
}
inline const ::se::common::Vector3& C_SpawnStoreReq::spawn_position() const {
  // @@protoc_insertion_point(field_get:se.test.C_SpawnStoreReq.spawn_position)
  return _internal_spawn_position();
}
inline void C_SpawnStoreReq::unsafe_arena_set_allocated_spawn_position(
    ::se::common::Vector3* spawn_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.spawn_position_);
  }
  _impl_.spawn_position_ = spawn_position;
  if (spawn_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:se.test.C_SpawnStoreReq.spawn_position)
}
inline ::se::common::Vector3* C_SpawnStoreReq::release_spawn_position() {
  
  ::se::common::Vector3* temp = _impl_.spawn_position_;
  _impl_.spawn_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::se::common::Vector3* C_SpawnStoreReq::unsafe_arena_release_spawn_position() {
  // @@protoc_insertion_point(field_release:se.test.C_SpawnStoreReq.spawn_position)
  
  ::se::common::Vector3* temp = _impl_.spawn_position_;
  _impl_.spawn_position_ = nullptr;
  return temp;
}
inline ::se::common::Vector3* C_SpawnStoreReq::_internal_mutable_spawn_position() {
  
  if (_impl_.spawn_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::se::common::Vector3>(GetArenaForAllocation());
    _impl_.spawn_position_ = p;
  }
  return _impl_.spawn_position_;
}
inline ::se::common::Vector3* C_SpawnStoreReq::mutable_spawn_position() {
  ::se::common::Vector3* _msg = _internal_mutable_spawn_position();
  // @@protoc_insertion_point(field_mutable:se.test.C_SpawnStoreReq.spawn_position)
  return _msg;
}
inline void C_SpawnStoreReq::set_allocated_spawn_position(::se::common::Vector3* spawn_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.spawn_position_);
  }
  if (spawn_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(spawn_position));
    if (message_arena != submessage_arena) {
      spawn_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, spawn_position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.spawn_position_ = spawn_position;
  // @@protoc_insertion_point(field_set_allocated:se.test.C_SpawnStoreReq.spawn_position)
}

// -------------------------------------------------------------------

// C_ItemReq

// uint32 item_id = 1;
inline void C_ItemReq::clear_item_id() {
  _impl_.item_id_ = 0u;
}
inline uint32_t C_ItemReq::_internal_item_id() const {
  return _impl_.item_id_;
}
inline uint32_t C_ItemReq::item_id() const {
  // @@protoc_insertion_point(field_get:se.test.C_ItemReq.item_id)
  return _internal_item_id();
}
inline void C_ItemReq::_internal_set_item_id(uint32_t value) {
  
  _impl_.item_id_ = value;
}
inline void C_ItemReq::set_item_id(uint32_t value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:se.test.C_ItemReq.item_id)
}

// int32 quantity = 2;
inline void C_ItemReq::clear_quantity() {
  _impl_.quantity_ = 0;
}
inline int32_t C_ItemReq::_internal_quantity() const {
  return _impl_.quantity_;
}
inline int32_t C_ItemReq::quantity() const {
  // @@protoc_insertion_point(field_get:se.test.C_ItemReq.quantity)
  return _internal_quantity();
}
inline void C_ItemReq::_internal_set_quantity(int32_t value) {
  
  _impl_.quantity_ = value;
}
inline void C_ItemReq::set_quantity(int32_t value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:se.test.C_ItemReq.quantity)
}

// -------------------------------------------------------------------

// C_MoneyReq

// int32 amount = 1;
inline void C_MoneyReq::clear_amount() {
  _impl_.amount_ = 0;
}
inline int32_t C_MoneyReq::_internal_amount() const {
  return _impl_.amount_;
}
inline int32_t C_MoneyReq::amount() const {
  // @@protoc_insertion_point(field_get:se.test.C_MoneyReq.amount)
  return _internal_amount();
}
inline void C_MoneyReq::_internal_set_amount(int32_t value) {
  
  _impl_.amount_ = value;
}
inline void C_MoneyReq::set_amount(int32_t value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:se.test.C_MoneyReq.amount)
}

// -------------------------------------------------------------------

// C_HealthReq

// int32 health = 1;
inline void C_HealthReq::clear_health() {
  _impl_.health_ = 0;
}
inline int32_t C_HealthReq::_internal_health() const {
  return _impl_.health_;
}
inline int32_t C_HealthReq::health() const {
  // @@protoc_insertion_point(field_get:se.test.C_HealthReq.health)
  return _internal_health();
}
inline void C_HealthReq::_internal_set_health(int32_t value) {
  
  _impl_.health_ = value;
}
inline void C_HealthReq::set_health(int32_t value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:se.test.C_HealthReq.health)
}

// -------------------------------------------------------------------

// C_MaxHealthReq

// int32 max_health = 1;
inline void C_MaxHealthReq::clear_max_health() {
  _impl_.max_health_ = 0;
}
inline int32_t C_MaxHealthReq::_internal_max_health() const {
  return _impl_.max_health_;
}
inline int32_t C_MaxHealthReq::max_health() const {
  // @@protoc_insertion_point(field_get:se.test.C_MaxHealthReq.max_health)
  return _internal_max_health();
}
inline void C_MaxHealthReq::_internal_set_max_health(int32_t value) {
  
  _impl_.max_health_ = value;
}
inline void C_MaxHealthReq::set_max_health(int32_t value) {
  _internal_set_max_health(value);
  // @@protoc_insertion_point(field_set:se.test.C_MaxHealthReq.max_health)
}

// -------------------------------------------------------------------

// C_ZoneStopReq

// -------------------------------------------------------------------

// C_ZoneStartReq

// -------------------------------------------------------------------

// C_ZoneResetReq

// -------------------------------------------------------------------

// C_ZoneDamageOffReq

// -------------------------------------------------------------------

// C_ZoneDamageOnReq

// -------------------------------------------------------------------

// N_ZoneStop

// -------------------------------------------------------------------

// N_ZoneStart

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace test
}  // namespace se

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_test_2ftest_5fmessages_2eproto
